import 'dart:ui' as ui;

import 'package:flutter/services.dart';
import 'package:miles/features/unlink/scene/scene_state.dart';

/// The owner's cast and world, decoded once per process.
///
/// Twelve WebP layers generated by the owner (BRAIN §227): two backdrops, a
/// door leaf, a lamp, a bird, an envelope, and six character poses. Decoded
/// off the bundle on first use and held for the process — the EmberBackground
/// sprite law, at asset scale. 401KB shipped against the 6MB ceiling.
///
/// [ensureLoaded] is idempotent and safe to race; failures leave the images
/// null and the scene falls back to its painted world, which is why a decode
/// error can never black out the ritual.
class SceneArt {
  SceneArt._();

  static ui.Image? backdropOut;
  static ui.Image? backdropIn;
  static ui.Image? door;
  static ui.Image? lamp;
  static ui.Image? bird;
  static ui.Image? envelope;

  static final Map<String, ui.Image> _chars = {};

  static Future<void>? _loading;
  static bool _ready = false;

  /// True only once EVERY layer has decoded.
  ///
  /// This used to read `backdropOut != null`, which is the first of twelve
  /// decodes — so for the rest of the load the painters were told the art was
  /// ready and then dereferenced `SceneArt.door!` on a null. On a test machine
  /// the whole load lands before the first paint and it never showed; on the
  /// owner's handset build 68 threw `_TypeError` out of
  /// `DoorstepPainter._paintStreet` and greyed the ritual.
  static bool get ready => _ready;

  static Future<void> ensureLoaded() => _loading ??= _load();

  static Future<ui.Image> _decode(String path) async {
    final bytes = await rootBundle.load(path);
    final codec =
        await ui.instantiateImageCodec(bytes.buffer.asUint8List());
    return (await codec.getNextFrame()).image;
  }

  static Future<void> _load() async {
    backdropOut = await _decode('assets/scene/backdrop_out.webp');
    backdropIn = await _decode('assets/scene/backdrop_in.webp');
    door = await _decode('assets/scene/door.webp');
    lamp = await _decode('assets/scene/lamp.webp');
    bird = await _decode('assets/scene/bird.webp');
    envelope = await _decode('assets/scene/envelope.webp');
    // Literal paths, one per sprite — the asset-hygiene orphan rule matches
    // on them, and a template string would read as six unreferenced files.
    _chars['m_glance'] = await _decode('assets/scene/m_glance.webp');
    _chars['m_calm'] = await _decode('assets/scene/m_calm.webp');
    _chars['m_worried'] = await _decode('assets/scene/m_worried.webp');
    _chars['f_calm'] = await _decode('assets/scene/f_calm.webp');
    _chars['f_worried'] = await _decode('assets/scene/f_worried.webp');
    _chars['f_letter'] = await _decode('assets/scene/f_letter.webp');
    // LAST line, deliberately: every field above must be non-null before a
    // painter is allowed to believe any of them are.
    _ready = true;
  }

  /// The character frame for this variant and mood, or null for the neutral
  /// figure — whose silhouette stays painted: `gender` is nullable in
  /// practice, and half a cast in bitmaps beside a differently-styled bitmap
  /// stranger would be worse than the quiet drawn figure.
  static ui.Image? charFor(PuppetVariant v, CharMood mood) {
    final prefix = switch (v) {
      PuppetVariant.male => 'm',
      PuppetVariant.female => 'f',
      PuppetVariant.neutral => null,
    };
    if (prefix == null) return null;
    final name = switch (mood) {
      CharMood.worried => '${prefix}_worried',
      CharMood.glance => prefix == 'm' ? 'm_glance' : 'f_calm',
      CharMood.calm => '${prefix}_calm',
      CharMood.letter => prefix == 'f' ? 'f_letter' : 'm_calm',
    };
    return _chars[name];
  }
}

/// What the character is doing with their face and hands right now.
enum CharMood { worried, glance, calm, letter }
