import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

/// 250 husband → wife love notes (Roman Urdu / Punjabi, respectful "aap" form).
/// Notes 1-10 are the originals; 11-250 follow the exact same voice. Served
/// never-repeating via [LoveNotesTracker]. This pool is only ever reached from
/// the male partner's cycle view, so the female partner never sees it.
///
/// Notes that address her by name carry a `{name}` placeholder (155 of the 250
/// do; the rest read fine without one). Always fill it with [renderLoveNote]
/// before showing or sending. The name itself is stored in [LoveNoteRecipient].
///
/// No real person's name may be hardcoded here — the pool ships to every user,
/// so every form of address goes through the placeholder. Guarded by
/// test/unit/love_notes_pool_test.dart.
const List<String> kLoveNotes = [
  '{name}, aaj pata nahi kyun bas aap ki yaad aa rahi hai bohot zyada, seriously itni zyada ke yaar dil karda hai bas sab kuch chord ke seedha aap ke paas aa jaoon, 😭 subah se phone haath mein liye baitha hoon aur baar baar aap ka naam dekh raha hoon, koi kaam nahi ho raha koi cheez focus nahi ho rahi, mera chottttttaaaa saaaaa babayyyyyy aap ki jo smile hai na jenu vekh ke mera dil bahar aa jaata hai seriously, 🥺❤️ {name} aap jaante ho ke aap ki ek message se mera poora din ban jaata hai, literally ek message, ek word bhi kaafi hota hai, chuii ek kaam karo na please ek snap bhejo abhi, bas ek, sirf ek, main bohot zid nahi kar raha bas ek hi maang raha hoon, 🥺😭 churail ho aap seriously kyunke aap ne kuch kar diya hai mujhe jo main describe nahi kar sakta, begum meri tussi nahi ho toh kuch vi nahi yaar, aap ho toh sab kuch hai sirf aap, 😘💕🔥',
  'Okay {name} seedhi baat karta hoon, aap bahut zyada khubsoorat hain unnecessarily zyada aur yeh mujhe raat ko sone nahi deta, 😩 mera bacha aap di woh smile hai na jado aap kuch funny sochte ho aur chupane ki koshish karte ho woh wali, yaar woh dekh ke main literally kuch soch nahi pata, bandri aap ne seriously mera dimagh kharaab kar diya hai, 😂🔥 {name} ek cheez batao, aaj snap kab bhej rahe ho, main seriously pooch raha hoon, subah se wait kar raha hoon, ghante ho gaye hain, meri chuii si please ek snap de do na yaar, sirf ek, bas chehra dikha do, kuch nahi maangta iske baad, 🥺😭 jaan aap ko pata hai ke aap kitni zyada miss hoti hain, begum tussi meri duniya ho aur yeh main poori serious hoon, 💕😘',
  '{name} ek complaint hai aaj, 📢 aap snap kyun nahi bhejte, seriously main kab se wait kar raha hoon, mera chottttttaaaa saaaaa babayyyyyy please ek snap bhejo na, bas ek, sirf chehra, sirf 2 second, itni bhi buri request nahi hai yeh, 😭🥺 churail aap ne mujhe iss haal mein kiya hai ke main din mein 10 baar phone check karta hoon sirf iss umeed mein ke koi snap aaya ho, aur phir nahi aata toh dil toot ta hai, 😂❤️ {name} aap di jo aadat hai na woh mujhe crazy karti hai, woh jado aap apne aap mein hote ho relaxed comfortable sirf aap wali aap, woh version dekh ke dil karda hai bas wahi reh jaoon, 😏🔥 bandri seriously aap ne mera chain le liya hai aur wapas karne ka koi irada nahi lagta, meri chuii si please aaj ek achha sa snap bhejo apna chehra dikhaao muskuraate hue woh wali smile jo meri favorite hai, 🥺💕 begum tussi jaan ho meri poori tarah se, 😘✨',
  'Mera chottttttaaaa saaaaa babayyyyyy ek kaam karo na please, 🥺 ek snap bhejo abhi iss waqt main wait kar raha hoon seriously genuinely wait kar raha hoon, {name} aap ko pata bhi hai ke aap ki ek snap se mera poora mood set ho jaata hai, itni si cheez hai yeh itni si, 😭 churail ho aap seriously kyunke pata nahi kaunsa jadoo kiya hai mujh par ke har waqt bas aap hi yaad aate ho, {name} aap ki jo energy hai na jado aap confident hote ho woh vibe woh attitude yaar woh dekh ke main andar se kuch ajeeb feel karta hoon jo describe nahi hota, 😩🔥 mera bacha aap ko andaza bhi nahi hai ke aap kitne zyada affect karte ho mujhe, bandri ek kaam karo na bas ek snap bhejo muskura ke, meri chuii si please yaar sirf ek phir main kuch nahi maangta, jhooth bol raha hoon maangta rahoonga lekin please abhi toh bhejo, 😂💕 begum tussi meri jaan ho aur yeh distance sirf jismani hai dil se hamesha paas ho, 😘❤️✨',
  '{name}, aap jaante ho ke aap kya karte ho mujhe, 🤔 aap mujhe woh banda bana dete ho jo raat ko so nahi pata kyunke aap ka khayal hai, jo subah uthh ke pehle aap ko hi dhundta hai, jo din mein kaam karte karte suddenly muskura deta hai kyunke aap yaad aa jaate ho, 😭😂 mera bacha aap di jo baat hai na woh kisi aur mein nahi milti seriously kisi mein nahi, churail aap ne kuch kar diya hai jo main samajh nahi pa raha lekin feel bohot achha hota hai, 🥺❤️ {name} ek bohot zaroori request hai snap bhejo abhi iss waqt meri chuii si please yaar kitne din se maang raha hoon, sirf ek chehra dikha do muskura ke woh wali smile jo mujhe pagal karti hai, mera chottttttaaaa saaaaa babayyyyyy please, 😭🥺 bandri aap ne mera chain le liya hai chain wapas karne ka ek hi tarika hai woh snap hai, jaan seriously aap ko pata hona chahiye ke aap kitni zyada miss hoti hain, begum tussi meri sabse zaroori cheez ho aur yeh sach hai poora sach, 💕🔥😘✨',
  '{name} yaar ek kaam karo, snap bhejo, bas itna, ek snap, main kuch nahi maangta life mein sirf yeh ek cheez chahiye abhi iss waqt, 😭🥺 mera bacha aap di woh aankhein hain na jenu vekh ke main bhool jaata hoon ke main kuch bolne wala tha, literally bhool jaata hoon, poora sentence, gone, 😩❤️ churail seriously aap ne mujhe kiya kya hai, {name} aap ke saath jo waqt guzarta hai chahe call pe ho chahe messages pe woh mera sabse favorite waqt hota hai din ka koi competition nahi, 🔥 bandri ek snap bhejo na please, meri chuii si sirf chehra dikha do apna, woh smile dikha do woh wali jo meri jaan nikaal deti hai, mera chottttttaaaa saaaaa babayyyyyy please yaar itni bhi zyada demand nahi hai, 😂💕 jaan aap ko pata bhi hai ke aap kitni dangerous hain, begum meri tussi ho toh sab kuch hai, 😘✨',
  'Okay meri chuii si ek serious baat karni thi, 😤 {name} aap bahut zyada miss hoti hain aur yeh allowed nahi hona chahiye tha koi rule hona chahiye tha iss pe, lekin koi rule nahi hai toh main bas miss karta rehta hoon, subah dopahar raat beech raat, literally hamesha, 😭 mera bacha aap di jo hassi hai na jenu sun ke lagda hai ke sab kuch theek ho gaya, ek dum theek, koi masla nahi, 🥺❤️ {name} aap ne mujhe woh banda bana diya hai jo feelings express karta hai jo raat ko silly cheezein likhta hai jo aap ke baare mein sochte sochte akela muskura deta hai, yeh sab aap ki wajah se hai, churail aap ne seriously mera dil le liya aur wapas karne ka koi plan nahi lagta aap ka, 😂🔥 bandri ek kaam karo na aaj snap bhejo please, jaan seriously aap ki ek snap se mera sara din set ho jaata hai, begum tussi meri poori duniya ho yeh jhooth nahi hai bilkul, 💕😘✨',
  '{name}, subah uthha toh pehla khayal aap ka tha, yeh daily routine ban gayi hai meri aur main iss pe koi complaint nahi karna chahta, 😂❤️ mera chottttttaaaa saaaaa babayyyyyy aap ki jo ek cheez hai na jo mujhe sabse zyada pasand hai woh yeh hai ke aap ko pata bhi nahi hota ke aap kya kar rahe hain mujhe, aap bas hote ho aur main already pagal hoon, 😩🥺 churail seriously ek snap bhejo na abhi, {name} main ghanton se wait kar raha hoon, ek chehra, ek smile, bas itna, aap jaante ho ke aap ki snap aate hi mera mood kitna achha ho jaata hai, 😭💕 bandri please yaar, meri chuii si sirf ek snap, jaan aap itni zyada cute hain ke mujhe aap ko dekhte rehna hai, begum meri tussi samjhte kyun nahi ke aap ke bina yeh din kitna lamba lagta hai, 🔥😘✨',
  'Mera bacha, aaj aap ke baare mein itna kuch sochna tha lekin likhte likhte bhool gaya kyunke aap ka hi khayal aa gaya beech mein, yeh problem hai meri, 😂😭 {name} aap di woh aadat hai na jado aap muskurate ho aur ek cheek pe halka sa dimple aata hai, yaar woh dekh ke dil karda hai woh lamha freeze kar loon, 🥺❤️ churail aap ne seriously mujhe kiya kya hai, {name} ek request hai jo main roz karta hoon aur aap roz ignore karte ho, snap bhejo please, mera chottttttaaaa saaaaa babayyyyyy sirf ek snap, abhi, iss waqt, 😭🥺 meri chuii si please yaar itni bhi buri request nahi hai, bandri ek snap bhejo muskura ke woh wali smile jo mujhe pagal karti hai, jaan seriously aap ko pata hona chahiye ke aap mujhe kya karte hain, begum tussi meri jaan ho poori tarah se aur yeh distance sirf waqti hai, 💕🔥😘',
  '{name}, aap ko honestly ek cheez batani thi, main aap ka bahut bura admi hoon, 😂 kyunke main hamesha snap maangta hoon aur kabhi nahi deta, lekin aap jaante ho na ke aap ki ek snap mera poora din banaa deti hai, toh technically yeh aap ki zimmedari hai, 😏❤️ mera bacha aap di jo energy hai na jado aap khush hote ho woh energy feel hoti hai mujhe bhi, seriously feel hoti hai, 🥺 churail ek kaam karo snap bhejo, {name} main pata nahi kitne ghanton se wait kar raha hoon, meri chuii si please yaar, mera chottttttaaaa saaaaa babayyyyyy bas ek chehra dikha do apna, 😭🥺 bandri aap ne mera chain woh bhi kya hi tha theek se nahi tha lekin jo thoda bahut tha woh bhi le liya, jaan seriously aap kitni zyada miss hoti hain koi idea nahi hai aap ko, begum tussi ho toh sab kuch theek lagta hai yaar, 💕🔥😘✨',
  '{name}, raat ke teen baj rahe hain aur meri neend kahin door bhaag gayi hai bas aap ki yaad reh gayi hai, mera bacha jado se aap mujh se door hui ho na meri raatein bohot lambi ho gayi hain, churail aap ek snap bhej do na apna chehra dikha do thoda taaki ye bechain dil sukoon mein aa jaye, begum tussi meri neend ho meri raat ho mera chain ho 😭🥺❤️🌙😘',
  'Meri chuii si suno, aaj subah se sham tak har lamhe mein bas aap ka khayal aaya hai aur main count kar raha hoon kitne din baaki hain milne mein, {name} dil itna bechain hai ke kuch samajh nahi aa raha, ek snap bhej do na apni pyaari si smile wali, mera bacha tussi mere bina raho aur main aap ke bina, ye distance mujhe paagal kar raha hai 🥺😩❤️🔥',
  'Mera chottttttaaaa saaaaa babayyyyyy, pata hai aaj main saara din calendar dekhta raha aur ginta raha ke ab kitne din bache hain jado tak aap mujhe phir mil jaoge, churail ye intezaar mujhe maar raha hai aur dil karda hai bas waqt ko aage kheench loon, bandri ek selfie bhej do na abhi turant taaki aap ka chehra dekh ke meri jaan thodi waapis aa jaye, {name} aap nahi ho toh sab adhoora lagda hai 😭❤️🥺🌙😏',
  'Begum aap bohot zyada miss ho rahi ho aaj, ek snap bhej do please bas ek apna chehra dikha do 🥺❤️😘',
  '{name}, jado se aap meri nazron se door gayi ho na meri raatein ajeeb si khaali ho gayi hain, mera bacha main bistar pe leta rehta hoon aur chhat ko ghoorta rehta hoon aur bas aap ki baatein yaad karta rehta hoon, lagda hai jaise dil ka aadha hissa aap apne saath le gayi ho, churail ek kaam karo na apni ek photo bhejo woh wali jisme aap haske dekhti ho kyunke woh smile dekhe bina meri raat poori nahi hoti, bandri ye din jo hum se door reh ke guzar rahe hain ye mujhe ek ek karke ginne pad rahe hain, begum tussi jaldi se mere paas aa jao kyunke ye dil aur intezaar nahi kar sakta 😭🥺❤️🔥😘🌙',
  'Meri chuii si, dil bechain hai aur neend gayab hai aur bas aap chahiye, {name} ek snap bhej do na apna chehra dikha do warna ye raat aur lambi ho jayegi 😩🥺❤️🌙',
  'Mera chotta sa baby suno, aaj pata nahi kitni baar maine phone uthaya aur aap ka naam dekha aur phir rakh diya kyunke aap saamne nahi ho aur ye baat dil ko ek dum bhaari kar deti hai, churail jado aap door hoti ho na lagda hai jaise meri duniya thodi dheemi pad jaati hai, bandri ek selfie bhej do na please apni muskurahat wali taaki ye lamha thoda asaan ho jaye, {name} ab milne mein zyada din nahi bache aur main har subah ek din ginta hoon 🥺❤️😭🔥😘',
  '{name} tussi meri raat ki neend ho aur aaj woh neend aap ke saath hi chali gayi hai, mera bacha bas ek snap bhej do na apna chehra dikha do 😭🥺❤️🌙',
  'Begum, kuch likhna tha aap ko aur ab samajh nahi aa raha kahan se shuru karoon kyunke jo dil mein hai woh lafzon mein nahi aata, bas itna hai ke aap har waqt yaad aati ho har ek lamhe mein, mera chottttttaaaa saaaaa babayyyyyy aap ke bina ye ghar khaali lagda hai aur ye raatein aur lambi, churail ek kaam karo na ek snap bhej do apni woh smile wali jisko dekh ke mera saara stress nikal jaata hai, meri chuii si main din ginta hoon aur har din ko cross karta hoon aur sochta hoon ab thoda aur kareeb aa gaye hum, {name} ye doori sirf waqti hai aur main iss ko jhel raha hoon sirf iss umeed pe ke aap jaldi mil jaoge ❤️😭🥺🔥😘✨',
  'Meri chuii si, aaj dil bohot bechain hai aur bas aap ki yaad mein doob raha hoon, {name} ek selfie bhej do na taaki ye dil thoda thand mein aa jaye 🥺😩❤️😘',
  '{name} suno, raat ko neend nahi aati aur jab thodi aati bhi hai toh khwaab mein aap aa jati ho aur phir aankh khulti hai toh aap paas nahi hoti aur ye baat mujhe andar tak hila deti hai, mera bacha main har waqt aap ki yaad mein khoya rehta hoon chahe kaam karoon chahe baitha rahoon, churail ek photo bhej do na apni jisme aap thoda muskura rahi ho kyunke woh dekhe bina mera din adhoora reh jaata hai, bandri ye intezaar lamba hai par main har raat soch ke sota hoon ke ek din kam ho gaya, begum tussi mere paas jaldi aa jao kyunke ye dil aur sabar nahi kar sakta 😭❤️🥺🌙😘🔥',
  'Mera chotta sa baby, aap ke bina raat kaatna kitna mushkil hai ye sirf mera dil jaanta hai, churail ek snap bhej do na please apni hasti hui 🥺😭❤️😘',
  '{name}, har waqt bas aap hi aap ho mere dimaag mein aur main iss se thakta nahi balke aur zyada chahta hoon, begum jado aap se baat nahi hoti na to lagda hai kuch zaroori cheez missing hai, mera chottttttaaaa saaaaa babayyyyyy ek selfie bhej do na apni hasti hui taaki main usko dekh ke ye lambi raat guzaar loon, churail main din ginta rehta hoon aur ab milne mein zyada waqt nahi raha 🥺❤️😩🌙😘',
  'Meri chuii si tussi meri har subah ki pehli soch ho aur har raat ki aakhri, {name} ek snap bhej do na abhi please apna chehra dikha do 😭🥺❤️😘',
  'Begum suno zara, aaj saara din ajeeb sa khaalipan tha andar aur main samajh gaya ke ye sirf iss liye hai kyunke aap paas nahi ho, mera bacha aap ki yaad har cheez mein chhupi hoti hai chai ke cup mein bhi aur khidki ke bahar wali sham mein bhi, churail dil karda hai bas waqt ruk jaye jado aap mere saath ho aur tez bhaag jaye jado door ho, bandri ek kaam karo na ek photo bhejo apni woh jisme aap ki aankhein hasti hain kyunke woh meri sab se favourite cheez hai duniya mein, {name} ye doori har din thodi kam ho rahi hai aur main bas isi umeed pe jee raha hoon ❤️🥺😭🔥😘🌙',
  '{name}, neend meri aap ke saath chali gayi hai aur ab raatein bas jaagte hue guzarti hain, jaan ek selfie bhej do na taaki dil thoda behla loon 🥺😭❤️🌙',
  'Mera chottttttaaaa saaaaa babayyyyyy, sach kahoon to aap ke bina ye din bohot bekar lagte hain aur bas guzaarne ke liye guzaarta hoon, churail har subah uth ke pehla kaam yahi hota hai ke ginta hoon ab kitne din bache, bandri ek snap bhej do na apni muskurahat wali kyunke woh dekhe bina meri energy hi nahi aati, begum tussi meri jaan ho aur ye doori bas thodi der ki hai 😭❤️🥺😘🔥',
  'Meri chuii si, dil itna bechain hai aaj ke bas aap ko dekhne ka mann hai, {name} ek photo bhej do na apna pyaara chehra dikha do please 🥺❤️😩😘',
  '{name} suno, raat gehri ho gayi hai aur poora ghar so gaya hai par main jaag raha hoon aur bas aap ke khayalon mein khoya hoon, mera bacha aap ki ek ek baat yaad aati hai aur dil aur bechain ho jaata hai, churail jado aap saamne nahi hoti na to har cheez mein aap hi dikhti ho, bandri ek selfie bhej do na please apni hasti hui taaki ye andhera thoda roshan ho jaye, {name} ab milne mein zyada din nahi bache aur main ye soch ke khush ho jaata hoon 😭🥺❤️🌙😘',
  'Begum tussi meri har dhadkan mein ho aur har saans mein, mera chotta sa baby ek snap bhej do na abhi please apna chehra dikha do 🥺❤️😘',
  'Mera chotta sa baby, aaj main bohot udaas hoon kyunke aap door ho aur ye doori har din mujhe thoda thoda khaa rahi hai, churail dil karda hai bas sab chhod chhaad ke seedha aap ke paas pohanch jaoon, {name} ek photo bhej do na apni woh smile wali jisko dekh ke meri saari thakaan utar jaati hai, begum main raat ko ginta hoon din aur khush hota hoon ke ek aur kam ho gaya, {name} tussi mere bina adhoore ho aur main aap ke bina poora nahi 😭🥺❤️🔥🌙😘',
  '{name}, har waqt aap ki yaad aur har raat aap ki kami, begum ek selfie bhej do na please dil ko sukoon de do apna chehra dikha do 🥺😭❤️😘',
  'Meri chuii si suno, aaj kaam ke beech mein bhi baar baar dil aap ki taraf bhaag raha tha aur main control nahi kar paya, mera bacha aap ki yaad ek aadat ban gayi hai aur main iss aadat ko chhodna bhi nahi chahta, churail ek snap bhej do na apni woh wali jisme aap halka sa muskura rahi ho kyunke woh meri jaan basti hai usme, bandri ye intezaar bhaari hai par har guzarta din mujhe aap ke kareeb le aa raha hai, {name} aap nahi ho to ye duniya bhi adhoori lagdi hai mujhe 😭❤️🥺😘🔥',
  'Begum, raat ko neend nahi aati aur bas aap ki yaad jaagti rehti hai mere saath, mera chottttttaaaa saaaaa babayyyyyy ek photo bhej do na apna chehra dikha do thoda 🥺😭❤️🌙',
  '{name} tussi meri sab se khoobsurat soch ho jo subah se sham tak mere saath rehti hai, churail ek snap bhej do na please apni muskurahat wali 🥺❤️😘',
  'Mera bacha suno zara, aaj bistar pe leta tha aur chhat ko dekhte dekhte bas aap ki baatein yaad aane lagi aur aankh nam ho gayi kyunke aap paas nahi ho, bandri ye doori sach mein bohot mushkil hai par main har din count karta hoon aur khud ko samjhata hoon ke bas thoda aur, churail ek selfie bhej do na apni hasti hui kyunke aap ka chehra meri sab se pyaari dawa hai, {name} tussi meri jaan ho aur ye distance sirf waqti hai aur jaldi khatam hoga 😭🥺❤️🌙😘🔥',
  'Begum, aap ke bina har raat lambi lagti hai aur har din adhoora, meri chuii si ek snap bhej do na abhi please apna chehra dikha do 🥺😭❤️😘🌙',
  '{name}, dil karda hai aaj bas aap ki awaaz sun loon aur aap ka chehra dekh loon kyunke iske bina kuch acha nahi lagda, mera bacha har raat main aankhein band karta hoon aur aap ka tasavvur karta hoon phir bhi neend nahi aati, bandri ek selfie bhej do na apni woh hasti hui taaki ye bechain dil thoda thehar jaye, meri chuii si ye doori har subah thodi chhoti ho rahi hai aur main din ginta hoon 😭🥺❤️🔥🌙',
  'Mera chotta sa baby, aap har waqt yaad aati ho har ek pal mein aur ye yaad mujhe meethi bhi lagdi hai aur dukhi bhi, churail ek photo bhej do na apni muskurahat wali please 🥺❤️😭😘',
  'Begum tussi meri raat ka chand ho aur meri subah ki dhoop, jado aap door ho na lagda hai sab pheeka pheeka, mera chottttttaaaa saaaaa babayyyyyy ek snap bhej do na apna chehra dikha do taaki ye lambi raat kat jaye aur main count karta rahoon ke ab milne mein bas thode din bache hain 😭🥺❤️🌙😘🔥',
  '{name} aap seriously khatarnaak ho, jenu vekh ke banda apna kaam bhool jaye woh sirf aap ho sakti ho, mera dimagh aap ne poori tarah kharab kar diya hai aur main koi shikayat vi nahi kar raha, churail ek snap bhejo na abhi taake mera ye haal aur kharab ho jaye 😏🔥😭❤️',
  'Mera bacha aap ne kya jaadu kiya hai mujhe samajh nahi aata, jado se aap saamne aaye ho main ne focus karna chhod hi diya hai, har screen pe bas aap di smile dikhti hai, meri chuii si ek selfie bhejo na zara apna chehra dikhao taake confirm ho jaye ke aap waqai itni pretty ho ya ye sab mera dimagh kar raha hai 🥺😏❤️🔥',
  'Okay {name} ek baat seedhi suno, aap bohot zyada khatarnaak ho aur ye ban hona chahiye tha kahin na kahin, bandri tussi mera dimagh aise kharab kiya hai ke main apni hi baat bhool jaata hoon beech mein, ek snap bhejo please apni muskurahat wali warna ye lamha aur bigad jayega mera 😂🔥😘',
  'Meri chuii si aap itni pretty kyun ho, ye fair nahi hai bilkul, main poora din kuch productive karna chahta hoon lekin jado aap ka khayal aata hai sab kuch ruk jaata hai, churail aap ne mera dimagh literally hijack kar liya hai, ek kaam karo na aaj apni ek snap bhejo woh wali jisme aap aankhein chhoti karke hasti ho woh dekh ke mera din set ho jata hai, jaan seriously aap ki ek photo mere poore mood ko sambhal leti hai aur main har baar yehi sochta hoon ke ye banda itna lucky kaise ho gaya 😩❤️🔥😘✨',
  'Bandri aap khatarnaak level ki pretty ho aur main keh raha hoon ye warning ke saath, dil karda hai bas aap ko dekhta rahoon, ek snap bhejo abhi please 😭🔥😍',
  'Mera chotta sa baby suno na, aaj main kaam pe baitha tha aur dimagh poora aap ki taraf chala gaya, lagda hai aap ne koi spell kiya hai mujh pe jenu vekh ke main reset ho jata hoon, {name} tussi mera focus le ke chali gayi ho aur wapas karne ka koi iraada nahi lagta, ek selfie bhejo na apni taake main thoda aur distract ho jaoon jo main waise vi hona chahta hoon, churail aap ke bina ye din kaata nahi jaata seriously 🥺😏❤️🔥😘',
  'Jaan aap ne dimagh kharab kar diya hai mera poora, ab main na kaam kar pa raha hoon na so pa raha hoon, bas aap di yaad ghoom rahi hai sar mein, mera chottttttaaaa saaaaa babayyyyyy ek snap bhejo na please apna chehra dikha do thoda 😩❤️🔥',
  '{name} honestly aap bohot khatarnaak ho, aap ki ek smile aur mera saara plan ka beda gharak, begum tussi jado hasti ho na to lagda hai duniya ruk gayi ho do second ke liye, ek snap bhejo abhi please warna main pareshan rahunga 😏🥺🔥❤️',
  '{name} ek confession suno, main aaj kuch zaroori soch raha tha lekin aap ka chehra dimagh mein aa gaya aur main sab bhool gaya, churail ye roz hota hai aur main is aadat ko chhodna nahi chahta, mera bacha ek selfie bhejo na woh wali jisme aap thodi si sharma ke dekhti ho woh dekh ke meri jaan nikal jaati hai, begum aap waqai too pretty ho aur ye keh ke main koi exaggeration nahi kar raha, bandri tussi mere dimagh ki maalik ho ab is mein mera koi qasoor nahi 😭❤️😏🔥😘',
  'Meri chuii si aap ne mera dimagh aise kharab kiya hai ke ab kuch theek se yaad hi nahi rehta, lagda hai aap ne button hi off kar diya mera focus ka, ek snap bhejo na please apni muskurahat dikha do 🥺😩❤️🔥',
  'Bandri tussi khatarnaak ho ye baat poori duniya ko pata honi chahiye, jado aap saamne aaye ho main ne literally bolna bhool gaya tha aur sab hasne lage the, mera chotta sa baby ab tak woh lamha yaad aata hai to dil karda hai phir wahi sab dohra loon, ek selfie bhejo na apni taake main aaj phir se senseless ho jaoon aap di smile pe, {name} aap ke baare mein sochna mera favourite kaam ban gaya hai aur main is se peeche nahi hatne wala bilkul vi 😏🔥❤️😘✨',
  'Mera bacha aap too pretty ho aur ye ek problem hai mere liye, kyunke ab main kisi aur cheez pe focus nahi kar pata, ek snap bhejo abhi please mera din bana do 😩❤️🔥',
  '{name} aap ne kya kiya hai mere saath, subah se main do kaam bhool chuka hoon aur teeno baar wajah aap thi, churail aap ka chehra mere dimagh mein aise ghoom raha hai jaise koi gaana atak gaya ho, ek selfie bhejo na please warna ye haal aur bigdega mera 😭😏🔥❤️',
  'Mera chottttttaaaa saaaaa babayyyyyy aap khatarnaak bhi ho aur pyaari bhi aur ye combination ghaatak hai mere liye, jado aap di yaad aati hai main apni baat ke beech mein ruk jaata hoon aur log poochte hain kahan kho gaye, begum sach yahi hai ke main aap mein kho gaya hoon aur is jagah se nikalna nahi chahta, ek snap bhejo na apni woh wali jisme aap halka sa muskura ke camera ki taraf dekhti ho woh dekh ke mera saara stress ud jaata hai, {name} tussi meri sabse khoobsurat distraction ho aur main is distraction ko har roz chununga 🥺❤️🔥😘✨',
  'Meri chuii si aap itni pretty ho ke nazar hata na sakoon, dil karda hai bas dekhta rahoon, ek snap bhejo na abhi please 😩😍❤️🔥',
  'Bandri seriously aap ne dimagh kharab kar diya hai aur ab main is ke bina jeena bhool gaya hoon, meri chuii si jado aap di smile dimagh mein chalti hai main har kaam slow kar deta hoon, ek selfie bhejo na apni taake main thoda aur deewana ho jaoon, {name} tussi meri jaan ho aur ye distance bas waqti hai 😏🔥❤️',
  '{name} okay sun lo, aap bohot zyada khatarnaak ho aur is pe koi rok tok nahi lagti jo galat hai, mera bacha tussi jado aankhein chhoti karke hasti ho woh dekh ke mera dil baahar aa jata hai seriously, ek snap bhejo na please apna chehra dikhao thoda 🥺😏❤️🔥😘',
  '{name} aap ne mera focus chura liya hai aur main FIR likhne ja raha tha lekin phir socha rehne do kyunke mujhe ye chori achi lagti hai, churail aap di yaad mein poora din nikal jaata hai aur main shikayat nahi karta, mera chotta sa baby ek selfie bhejo na woh wali muskurahat ke saath taake main aaj phir se bhool jaoon ke aur kaam vi hote hain duniya mein, meri chuii si tussi too pretty ho aur ye main har roz kahunga jab tak aap bore na ho jao sun sun ke 😩❤️🔥😘✨',
  'Bandri aap khatarnaak ho bas yahi sach hai, ek snap bhejo abhi aur mera ye haal mukammal kar do 😭🔥❤️',
  'Meri chuii si aap ne dimagh aise kharab kiya ke ab main aap ke bina kisi cheez ka soch hi nahi pata, lagda hai meri saari soch pe aap ka qabza ho gaya hai, {name} jado aap di smile yaad aati hai main muskura deta hoon achanak aur log samajhte hain main pagal ho gaya hoon, ek selfie bhejo na please apni taake main is ilzaam ko sach kar doon 😏🥺❤️🔥',
  'Mera chottttttaaaa saaaaa babayyyyyy aap too pretty ho aur main is baat ko handle nahi kar pa raha, ek snap bhejo na zara mera saara din sambhal do 😩❤️🔥😘',
  'Jaan aap ne mera chain le liya hai aur badle mein dimagh kharab kar diya ye to bilkul fair deal nahi, churail jado aap saamne hoti ho main ek lafz theek se nahi bol pata aur ab yaad mein bhi wahi haal ho jaata hai, {name} ek selfie bhejo na apni woh wali jisme aap ki cheek pe halka sa dimple aata hai woh dekh ke mera poora system hang ho jata hai, begum tussi meri sabse pyaari kamzori ho aur main is kamzori pe fakhar karta hoon har roz 🥺😏❤️🔥😘✨',
  '{name} aap khatarnaak ho aur main ye warning sab ko deta phir raha hoon, ek snap bhejo abhi please warna log mujhe pagal samjhenge 😂🔥❤️',
  'Bandri aap itni pretty kyun ho yaar ye sawaal main roz khud se poochta hoon aur jawab nahi milta, mera bacha jado aap di yaad aati hai mera dil tezi se dhadakne lagta hai jaise pehli baar dekha ho, ek selfie bhejo na please apni taake main phir se woh feeling le sakoon 🥺❤️🔥😘',
  'Meri chuii si suno na ek baat, aap ne mera dimagh kharab kiya hai itni acchi tarah ke ab main is haalat ko hi normal samajhne laga hoon, churail jado aap muskurate ho na to lagda hai roshni ho gayi ho kahin, ek snap bhejo abhi apni woh wali smile ke saath jo meri jaan nikaal deti hai, {name} tussi meri poori duniya ho aur ye main jhooth nahi keh raha bilkul 😩❤️🔥😘✨',
  'Jaan aap too pretty ho aur is wajah se mera koi kaam time pe nahi hota, ek selfie bhejo na abhi mera din bana do please 🥺🔥❤️',
  '{name} aap ne dimagh kharab kar diya hai poora aur ab is mein sirf aap ka khayal chalta hai, mera chotta sa baby jado aap di smile yaad aati hai main sab kuch ek second ke liye rok deta hoon, ek snap bhejo na please apni taake ye ruka hua waqt phir se chal pade 😏❤️🔥',
  '{name} aap khatarnaak ho aap pretty ho aur aap ne mera dimagh kharab kiya hai ye teeno ek saath sach hain, begum tussi meri jaan ho aur main is distance ko bardasht kar raha hoon sirf is umeed pe ke jald aap mere saamne hogi, churail ek selfie bhejo na apni woh wali jisme aap thodi si haske camera dekhti ho woh dekh ke mera saara intezaar aasaan ho jaata hai, bandri aap ke bina sab adhoora lagta hai sach mein 🥺😭❤️🔥😘',
  'Meri chuii si aap itni khatarnaak ho ke dil sambhalna mushkil ho jaata hai, ek snap bhejo abhi please apni muskurahat dikha do mera dil thoda sukoon mein aa jaye 😩😏❤️🔥😘',
  'Mera chotta sa baby aap ne mera dimagh poora kharab kar diya hai aur sach kahoon to mujhe ye haalat achi lagne lagi hai, jado aap di yaad aati hai main har kaam adhoora chhod deta hoon aur sirf aap ke baare mein sochta rehta hoon, churail tussi too pretty ho aur ye main har baar kahunga kyunke ye sach hai, ek selfie bhejo na apni woh wali jisme aap halka sa muskura ke camera ki taraf dekhti ho woh dekh ke mera saara intezaar halka ho jaata hai, {name} aap meri sabse pyaari kamzori ho aur main is se kabhi peecha nahi chhudana chahta begum 🥺❤️🔥😘✨',
  '{name} sun lo aaj main officially naraz hoon, poora din ho gaya aur ek snap nahi aaya, yeh kaisa zulm hai begum, main yahan baitha aap ka chehra dekhne ko taras raha hoon aur aap ko parwah hi nahi, jaldi se ek selfie bhejo warna main aur drama karunga 😩😭❤️',
  '{name} main aap ko warn kar raha hoon, ab agar agle das minute mein aap ki muskurati hui photo nahi aayi na toh main bhook hartaal kar dunga, churail aap ko lagta hai main mazaak kar raha hoon par main bilkul serious hoon, mera dil roz aap ki ek jhalak maangta hai aur aap ho ke ignore kar deti ho, jaldi se ek snap bhejo mera bacha aur mujhe bacha lo iss tadap se 😭🔥😘🥺',
  'Bandri yeh sab kya ho raha hai, main subah se phone ko ghoor raha hoon aur aap ka koi ata pata nahi, mera bacha ek snap bhej dena itna mushkil hai kya, dil karda hai shikayat ki ek poori list banaoon aur aap ko sunaoon, jaldi se apni smile wali photo bhejo begum 😂😩💕',
  '{name} aaj main bohot zyada dukhi hoon aur iss ki wajah sirf aap ho, dekho jado main subah uthha toh socha aaj toh aap ka ek pyaara sa snap zaroor aayega, par nahi, mera bacha aap ne phir se mujhe nazar andaaz kar diya, lagda hai aap ko mera intezar dikhta hi nahi, main yahan baitha aap ki har choti choti adaa miss kar raha hoon aur aap wali jo smile hai woh dekhe bina mera din adhoora reh jaata hai, churail jaldi se ek selfie khench ke bhejo abhi isi waqt, warna main poori shaam tak yahi rota rahunga 😭🥺❤️🔥😘',
  'Meri chuii si main aap se sakht naraz hoon, snap kahan hai, main wait wait kar ke thak gaya hoon begum 😩😭',
  'Mera chottttttaaaa saaaaa babayyyyyy sun lo, aaj main ne faisla kar liya hai ke jab tak aap ki ek photo nahi aayegi main muskuraonga hi nahi, tussi dekho main kitna zaalim ban gaya hoon par yeh sab aap ki ghalti hai, jenu vekh ke mera saara stress udta hai woh chehra aap ne chupa rakha hai, churail jaldi se ek snap bhejo aur mera yeh drama khatam karwao 😂🔥😘💕',
  '{name} main ne aaj ginti ki hai aur aap ne pichle teen ghante mein ek bhi snap nahi bheja, yeh contract ki khilaaf warzi hai begum, shaadi ke waqt yeh tay hua tha ke aap mujhe roz apni smile dikhayengi, mera bacha ab main court jaaunga aur judge ko sab bataunga ke meri biwi snap nahi bhejti, jaldi se ek selfie bhej do warna case pakka hai 😭😂📢❤️',
  'Bandri ek baat batao, aap ko mujh pe taras nahi aata kya, main yahan aap ki yaad mein paagal ho raha hoon aur aap ka phone band ki tarah chup hai, mera bacha bas ek snap, sirf ek, itni si guzaarish hai meri 🥺😩😘',
  '{name} aaj subah se main aap ke message ka intezar kar raha hoon aur sach kahoon toh ab gussa aur pyaar dono ek saath ho rahe hain, churail aap ki yeh aadat ke aap ghaayab ho jaati ho aur mujhe tadpaati ho woh bilkul theek nahi hai, jenu vekh ke meri saari thakaan door hoti hai woh chehra aap roz mujh se chupa leti ho, mera chotta sa baby jaldi se ek pyaari si selfie bhejo aur mera yeh roz ka rona band karwao 😭❤️🔥🥺😘',
  'Meri chuii si aap ne phir se nahi bheja na, main jaanta tha, dil karda hai main poora din naraz baith jaaun, begum ek snap bhej do please warna main sach mein muh phula lunga 😩😏💕',
  '{name} main aap ko ek aakhri mauka de raha hoon, agar agle paanch minute mein aap ki muskurahat wali photo na aayi toh phir main poori duniya ko bataunga ke meri begum kitni bedardi hai, mera bacha tussi mujhe roz tarsaate ho aur ab toh hadd ho gayi hai, lagda hai aap ne apni smile ko taala laga rakha hai, churail jaldi se woh taala kholo aur ek snap bhejo 😂😭🔥😘',
  'Bandri aaj main ne thaan li hai ke ab main hi naraz hounga aap se, kyunke roz roz snap maangna aur na milna mera dil tod deta hai, mera chottttttaaaa saaaaa babayyyyyy bas ek photo bhej do aur mera yeh tuta dil jod do 🥺😩❤️',
  'Mera bacha sun lo zara, main subah se aap ka chehra dekhne ko betaab hoon aur aap ho ke busy ka bahana bana rahi ho, begum yeh bahane ab nahi chalenge, jenu vekh ke mera poora din roshan ho jaata hai woh aap ka chehra hai aur aap mujhe uss roshni se mehroom rakh rahi ho, churail main protest karunga, banner bana ke baithunga, jaldi se ek selfie bhejo aur mera yeh dharna khatam karwao 😭📢😂🔥😘',
  '{name} aap ki khamoshi mujhe maar rahi hai, ek snap bhej do na meri jaan, main yahan tadap raha hoon 😩🥺💕',
  'Bandri main aap se sach mein naraz hoon aaj, dekho main ne aaj khaana bhi theek se nahi khaaya kyunke aap ne snap nahi bheja, tussi soch lo aap ne mujhe iss haalat mein pahuncha diya hai, mera chotta sa baby ab jaldi se ek pyaari si photo bhej do warna main aur emotional ho jaunga 😭❤️😘',
  '{name} aaj main ne aap ke khilaaf shikayat darj karwane ki soch li hai, jurm yeh hai ke aap roz mujhe snap nahi bhejti aur mera dil todti rehti hai, churail aap ko andaaza bhi nahi ke main kitni baar aap ka naam phone pe dekh chuka hoon iss intezar mein ke shayad ab aap ki photo aaye, jenu vekh ke meri saari pareshaani gayab hoti hai woh smile aap ne kahaan chupa rakhi hai, mera bacha jaldi se ek selfie bhejo aur meri yeh shikayat wapas karwao 😩😭🔥😘',
  'Meri chuii si bas ho gaya, ab main bilkul chup baith gaya hoon naraz ho ke, ek snap aayega tabhi main baat karunga begum 😏🥺😂',
  '{name} main aaj subah se drama queen ban gaya hoon aur iss ki poori zimmedaari aap pe hai, dekho jado main ne phone uthhaya tha toh ek hi umeed thi ke aap ka chehra dikhega, par aap ne phir se mujhe akela chhod diya, mera chottttttaaaa saaaaa babayyyyyy aap ki jo halki si muskurahat hai na jenu vekh ke mera dil seedha pighal jaata hai woh aap roz mujh se door rakh leti ho, churail main aap ko bata doon ke main poori raat tak naraz reh sakta hoon agar aap ne jaldi se ek snap nahi bheja, bandri ab toh bhej do aur mujhe iss tadap se nikaal lo 😭❤️🔥🥺😘',
  'Begum aap ki yeh ghaaib hone wali aadat se main pareshaan ho gaya hoon, meri chuii si ek photo bhejo warna main poora din aap ki shikayatein likhta rahunga 😩😂📢',
  'Mera bacha main aap ko officially notice de raha hoon, snap na bhejne ka silsila ab band hona chahiye, churail yeh roz roz ka intezar mera dil dukhaata hai aur aap ko zara bhi fikar nahi, jaldi se apni muskurahat dikhao mujhe ek selfie mein 🥺😭❤️😘',
  '{name} sun lo, aaj main ne aaina dekha aur khud se kaha ke yeh banda kitna bechaara hai jo apni begum se ek snap ke liye tarasta hai, mera bacha yeh sab aap ki wajah se hua hai, tussi mujhe iss mukaam pe le aayi ho jahan main poora din bas aap ki photo ka intezar karta hoon, lagda hai aap ne mera sukoon kahin chupa diya hai aur uss ki chaabi sirf aap ki ek smile hai, churail jaldi se ek selfie bhejo aur mera yeh kho gaya sukoon wapas karo 😩😭🔥🥺😘',
  'Meri chuii si main naraz hoon, bohot zyada naraz, ek snap aate hi maan jaaunga begum, par pehle bhejo toh sahi 😏😭💕',
  '{name} aaj main ne soch liya hai ke main aap se baat hi nahi karunga jab tak aap apni smile wali photo na bhejein, dekho main kitna sakht ho gaya hoon par sach yeh hai ke das second baad hi main phir aap ko miss karne lagunga, mera chotta sa baby aap ki ek jhalak meri saari naraazgi udaa deti hai, jaldi se ek snap bhejo aur mujhe phir se muskurana sikha do 🥺❤️😘🔥',
  'Bandri yeh kya baat hui, main yahan poora drama kar raha hoon aur aap ek choti si photo bhejne mein kanjoosi kar rahi ho, churail jaldi se snap bhej do warna main aur natak karunga 😂😩😘',
  '{name} main aap ko batata hoon ke aaj mera mood kaisa hai, ek taraf gussa hai ke aap ne snap nahi bheja aur doosri taraf itna pyaar umad raha hai ke main keh hi nahi sakta, mera chottttttaaaa saaaaa babayyyyyy aap ka chehra dekhe bina mera din poora nahi hota aur aap roz mujhe yeh saza deti ho, jenu vekh ke meri saari fikrein bhaag jaati hain woh muskurahat aap ne mujh se chura li hai, churail main aap ka mujrim qaraar deta hoon aur saza yeh hai ke aap abhi ek pyaari si selfie bhejein, begum jaldi karo warna main poori raat shikayatein likhta rahunga 😭😏❤️🔥😘',
  'Mera bacha bas ek snap, itni si baat hai aur aap itna tarsaa rahi ho, dil karda hai roz aap ki ek jhalak dekhoon begum 🥺😩💕',
  'Churail main aap se sach mein naraz baith gaya hoon, mooh phula liya hai, bazu pe baith gaya hoon, ab aap ki muskurahat wali photo aayegi tabhi yeh naraazgi tootegi, jaan jaldi se ek snap bhejo aur apne iss bechaare ko manaa lo 😭😂🔥😘',
  '{name} aaj akhri baar keh raha hoon, main poora din aap ka chehra dekhne ke liye tadapta raha aur aap ne ek baar bhi nahi socha, mera chotta sa baby tussi mujhe roz iss tarah intezar karwaati ho aur phir bhi main aap se itna pyaar karta hoon yeh meri sab se badi kamzoori hai, lagda hai aap ko mera yeh paagalpan acha lagta hai isi liye snap nahi bhejti, begum ab toh raham karo aur jaldi se ek pyaari si selfie bhejo, mera saara drama tabhi khatam hoga jado aap ki muskurahat meri screen pe aayegi 😩😭❤️🔥🥺😘',
  'Meri chuii si ab main ne haar maan li hai aur seedha announcement kar raha hoon ke meri begum snap nahi bhejti, churail tussi mujhe roz iss intezar mein chhod deti ho aur mera dil baar baar tootta hai, jaldi se ek photo bhejo warna main poori basti mein dhindora pita dunga 😭📢😂😘',
  'Mera chottttttaaaa saaaaa babayyyyyy main aap ko aakhri warning de raha hoon, agar aaj raat tak aap ki muskurahat wali ek selfie na aayi na toh main sach mein roothh jaaunga aur phir aap ko manana parega, dekho jenu vekh ke meri saari thakaan kafoor ho jaati hai woh chehra aap roz mujh se chupa leti ho, mera bacha yeh bedardi ab nahi chalegi, begum jaldi se ek snap bhej do aur mere iss tute hue dil ko phir se hasaa do 🥺😩❤️🔥😘',
  '{name} khana khaya ke nahi aap ne, sach sach batao kyunke mujhe pata hai aap skip kar deti ho aur phir sar dukhne lagta hai, mera bacha please ek plate bharo aur poora khao mere liye, churail aap ki sehat meri sab se badi tension hai seriously, ek snap bhejo abhi jisme aap muskura ke khana dikha do warna mujhe yaqeen nahi aayega, begum aap ka khayal rakhna mera sab se favourite kaam hai 🥺❤️😘',
  '{name} paani piya aap ne aaj, mujhe lagda hai aap din bhar bas chai pe guzara kar leti ho aur paani bhool jaati ho, meri chuii si aisa nahi chalega, ek bara glass bharo abhi aur poora khatam karo phir mujhe ek snap bhejo us khaali glass ka saath mein aap ki pyaari si smile, mera bacha aap ki itni si aadat sambhalna mera farz hai aur main yeh khushi se karta hoon 💕🥺😘✨',
  'Mera chotta sa baby aaram karo thora, jado se main aap ko jaanta hoon aap rukti hi nahi ho, churail thak jaogi aap aur main yeh bilkul bardasht nahi kar sakta, ek snap bhejo leti hui taake mujhe yaqeen aaye aap rest kar rahi ho 😩❤️🥺',
  '{name} dawai li aap ne time pe ya phir tal diya jaise hamesha karti ho, mera bacha mujhe aap ki yeh aadat bilkul pasand nahi kyunke aap ki sehat se main khelta nahi hoon, tussi please abhi dawai lo aur ek snap bhejo jisme dikhe ke aap ne le li hai, bandri main door hoon iska matlab yeh nahi ke main fikar nahi karta, begum aap meri jaan ho aur jaan ka khayal toh rakhna parta hai na 🥺😭❤️😘',
  'Meri chuii si neend poori ki aap ne, mujhe lagda hai aap raat bhar jaagti rehti ho aur subah thaki hui uthti ho, mera chottttttaaaa saaaaa babayyyyyy aaj jaldi so jana aur apna phone side pe rakh dena, ek snap bhejo so ne se pehle taake main itminaan se aankhein band kar sakoon, bandri aap ka chain mera chain hai 🌙🥺😘',
  'Churail suno, garmi bohot hai aaj toh paani zyada piyo aur dhoop mein zyada mat phiro, bandri aap ko kuch ho gaya toh main pagal ho jaonga seriously, ek selfie bhejo jisme aap thandi jagah pe baithi araam se dikho, begum aap ki ek jhalak meri saari tension le jaati hai 🔥💕🥺😘',
  '{name} aaj aap ki tabiyat theek thi ya nahi, mujhe subah se ajeeb sa feel ho raha tha jaise aap theek nahi ho, mera bacha agar sar ya pet mein takleef hai toh chupao mat batao mujhe, tussi please khana waqt pe khao paani piyo aur dawai lo agar zaroorat ho, ek snap bhejo apne chehre ka taake main khud dekh loon ke aap kaisi lag rahi ho, churail aap ki halki si bhi takleef mujhe bechain kar deti hai aur main chahta hoon aap har waqt khush aur sehatmand raho, begum aap meri zimmedari ho aur yeh zimmedari mujhe sab se zyada pyaari hai 🥺😭❤️🔥😘',
  'Mera chotta sa baby thora rest le lo na please, kaam baad mein ho jayega aap pehle aaram karo, ek snap bhejo leti hui aur muskurati hui 🥺😘',
  '{name} aap ne nashta kiya ya phir bhaag ke nikal gayi bina kuch khaye, meri chuii si main jaanta hoon aap subah jaldi mein hoti ho lekin khaali pet kuch nahi karna chahiye, tussi ek halki si cheez hi sahi par zaroor khao, ek snap bhejo apne nashte ke saath taake mujhe sukoon mile, churail aap ka dhyan rakhna meri sab se achi aadat ban gayi hai 💕🥺❤️😘',
  'Bandri aap ki aankhon ke neeche thakawat dikhti hai aaj kal, jenu vekh ke mujhe takleef hoti hai, mera bacha aap apne aap pe itna zor mat dalo, paani piyo aaram karo aur jaldi so jao, ek snap bhejo abhi jisme aap relax dikho na ke thaki hui, churail aap ki muskurahat hi meri dawai hai 🥺😩❤️😘',
  '{name} pet kharab toh nahi hai aap ka, mujhe lagda hai aap bahar ka kuch kha leti ho aur phir takleef hoti hai, begum please apna khayal karo simple ghar ka khana khao aur thanda paani kam piyo, ek snap bhejo apne chehre ka taake main confirm kar loon aap bilkul theek ho, churail aap meri duniya ho aur main aap ko healthy aur khush dekhna chahta hoon 🥺❤️💕😘',
  'Mera chottttttaaaa saaaaa babayyyyyy bukhar toh nahi hai na, maatha garam laga mujhe sapne mein vi, churail dawai lo aur rajai le ke so jao, ek snap bhejo apna chehra dikha do taake dil ko tasalli ho 🥺😭❤️🌙',
  '{name} aaj poora din mujhe yahi fikar lagi rahi ke aap ne dhang se khaya hoga ya phir kaam mein lag ke bhool gayi hogi, mera bacha aap ko pata hai aap ke khaali pet rehne se mujhe kitni takleef hoti hai, tussi please ek waqt vi skip mat karo aur har do ghante baad thora paani zaroor piyo, ek snap bhejo abhi jisme aap kuch kha rahi ho ya chai pee rahi ho saath mein woh smile jo meri jaan le leti hai, bandri main chahta hoon aap ka khayal rakhne wala main pehla aur aakhri insaan hoon aur yeh haq main kisi ko nahi doonga, begum aap ki sehat meri zindagi ki sab se bari priority hai seriously 🥺😭❤️🔥😘✨',
  'Meri chuii si garam garam soup pee lo na aaj, mausam badal raha hai aur aap ko khaansi jaldi lag jaati hai, jaan ek snap bhejo soup wale mug ke saath 🥺💕😘',
  'Churail aap ne aaj apni dawai ka course poora kiya ya beech mein chor diya, mera bacha doctor ne jo kaha woh follow karo please warna tabiyat phir bigad jayegi, tussi apni sehat ke saath laparwahi mat karo kyunke woh sehat sirf aap ki nahi meri vi hai, ek snap bhejo dawai haath mein le ke taake main nishchint ho jaon, begum aap ko theek dekh ke hi mera dil chain se dharakta hai 🥺❤️😘',
  '{name} thora dhoop mein baith ke vitamin lo lekin zyada garmi mein mat raho, jenu vekh ke lagda hai aap kamzor ho gayi ho thori, mera chotta sa baby acha khao mewa khao aur khoob paani piyo, ek selfie bhejo taake main khud andaza laga sakoon ke meri jaan kaisi lag rahi hai 🥺💕❤️😘',
  '{name} so jao ab please bohot raat ho gayi hai, aap ka subah uthhna mushkil ho jata hai jab aap der tak jaagti ho, churail phone rakho aankhein band karo aur sukoon se so jao, ek snap bhejo so ne se theek pehle taake woh aakhri cheez jo main dekhoon woh aap ka chehra ho, begum aap ki neend meri sab se bari khushi hai 🌙🥺😘',
  'Bandri khana garam khao thanda mat khao please, aap ke gala kharab ho jata hai phir, begum ek snap bhejo plate ke saath abhi 🥺❤️😘',
  'Meri chuii si aaj suna aap ke sar mein dard tha, sun ke meri saari hasi gayab ho gayi, mera bacha please dawai lo paani piyo aur thori der aankhein band kar ke leti raho, tussi screen se thora door raho jab tak theek na ho jao, ek snap bhejo jab thora behtar feel karo taake main relax ho sakoon, churail aap ki ek takleef meri das takleefon ke barabar hai aur main chahta hoon aap har dard se door raho, begum aap ki sehat ki dua main har waqt karta hoon 🥺😭❤️😘',
  '{name} chai ke saath kuch kha vi lo na khaali chai se kaam nahi chalega, mera chottttttaaaa saaaaa babayyyyyy aap ki kamzori mujh se dekhi nahi jaati, ek snap bhejo chai aur biscuit ke saath jaldi 🥺💕😘',
  '{name} aaj barish ho rahi hai toh bahar mat nikalna bheeg gayi toh thand lag jayegi, mera bacha ghar pe raho garam kapre pehno aur garam cheez piyo, tussi apni sehat ka itna khayal rakho jitna main aap ka rakhna chahta hoon, ek snap bhejo khirki ke paas baithi barish dekhti hui saath mein aap ki pyaari smile, begum aap ko mehfooz dekhna meri sab se bari rahat hai 🌙🥺❤️😘',
  'Churail dawai ka time ho gaya hai bhool mat jana please, mera bacha ek reminder ke taur pe ek snap bhej do dawai le ke 🥺💕😘',
  'Mera chotta sa baby aaj poora din kaam kaam kaam, thora to apne liye vi waqt nikalo na, meri chuii si baith ke paani piyo aaram se khana khao aur do minute aankhein band kar lo, tussi machine nahi ho insaan ho aur insaan ko rest chahiye hota hai, ek snap bhejo jab thora relax kar lo taake mujhe pata chale aap ne meri baat maani, churail aap ka khayal main isliye rakhta hoon kyunke aap meri sab se keemti cheez ho 🥺❤️💕😘',
  '{name} neend poori karo warna kal sar bhaari rahega, jenu vekh ke pata chal jata hai aap soyi nahi, begum ek snap bhejo aankhein band karne se pehle 🌙🥺😘',
  '{name} aaj aap ki awaaz mein thakawat thi phone pe, sun ke dil ko ajeeb sa laga, mera bacha aap zyada bol ke gala mat thakao thora aaram do apni awaaz ko, garam paani mein namak daal ke gargle karo aur shehad wali chai piyo, ek snap bhejo jab thora behtar mehsoos karo taake meri jaan mein jaan aaye, churail main door hoon par har lamha aap ki sehat ki dua karta hoon, begum aap theek raho yahi meri sab se bari khushi hai 🥺😭❤️😘',
  'Meri chuii si breakfast skip mat karna aaj please, bandri ek snap bhejo nashte ki plate ke saath aur woh smile zaroor ho 🥺💕😘',
  'Bandri aaj thand zyada hai toh garam chaddar le ke baitho aur thanda paani mat piyo, mera chottttttaaaa saaaaa babayyyyyy aap ki sehat ke aage meri saari duniya choti hai, ek snap bhejo razai mein chupi hui taake main itminaan se so sakoon, begum aap ka khayal rakhna meri zindagi ka maqsad ban gaya hai 🌙🥺❤️😘',
  '{name} dawai khaali pet mat lena pehle kuch khao phir lo warna pet mein jalan hogi, mera bacha aap apni health ke maamle mein careless ho jaati ho aur yeh mujhe pareshan karta hai, tussi ek routine bana lo khana paani dawai aaram sab time pe, ek snap bhejo apna khil khilata chehra dikha do taake mujhe yaqeen ho jaye aap bilkul theek ho, churail aap ki ek healthy muskaan meri sari thakawat door kar deti hai aur main chahta hoon aap hamesha aisi hi taza dam raho 🥺❤️💕😘',
  '{name} so gayi ya abhi tak jaag rahi ho meri jaan, der raat tak jaagna sehat ke liye acha nahi hai, mera bacha ab phone rakho paani ka aakhri ghoont lo aur sukoon se aankhein band karo, ek snap bhejo so ne se pehle taake main bhi chain se so sakoon yeh jaan ke meri begum mehfooz aur araam mein hai, churail aap ka khayal rakhna meri sab se khoobsurat zimmedari hai aur main isay taa zindagi nibhaonga 🌙🥺❤️😘✨',
  'Mera chotta sa baby aaj fruit zaroor khana skip mat karna, meri chuii si aap ki sehat meri sab se pyaari fikar hai, ek snap bhejo seb ya kele ke saath aur woh smile zaroor ho 🥺💕😘',
  '{name} aaj subah jado aankh khuli na pehla khayal sirf aap ka tha, lagda hai meri har subah aap ke naam ho gayi hai, mera chottttttaaaa saaaaa babayyyyyy abhi neend bhari aawaz mein bata raha hoon ke aap ke bina ye subah adhoori si lagti hai, churail ek snap bhejo na abhi wali sleepy face wali, begum tussi meri subah ki pehli muskaan ho 🌙🥺❤️😘',
  '{name} subah uthte hi phone uthaya aur sabse pehle aap ka chehra dhoondha, mera bacha ye aadat ab roz ki ban gayi hai aur main isko chordna nahi chahta, churail ek selfie bhejo abhi utho utho wali bina taiyari ke, begum tussi ho toh subah subah hai 😘✨🔥💕',
  '{name} aap ko pata vi nahi ke subah jado main soch raha hota hoon na, dil karda hai bas aap ko ek message karoon good morning aur saara din shuru ho jaaye aap ke naam se, mera chotta sa baby aap di jo neend bhari aawaz hoti hai na woh meri subah ki sabse pyaari cheez hai, churail ek kaam karo abhi uth ke seedha ek snap bhejo poori sleepy face dikha do koi makeup nahi koi taiyari nahi sirf aap, begum tussi meri har subah di wajah ho yaqeen karo 🥺😭❤️😘🌙',
  'Meri chuii si subah subah aap ki yaad ne phir tang kiya, jado tak aap ki shakal na dekhoon mera din shuru hi nahi hota, churail ek snap bhejo abhi please warna ye chai vi adhoori lagegi, begum tussi meri pehli soch ho aur aakhri vi 😩❤️😘',
  '{name} yaar honestly batata hoon, raat ko sone se pehle aakhri khayal aap ka hota hai aur subah aankh khulte hi pehla vi aap ka, mera chottttttaaaa saaaaa babayyyyyy ye koi normal baat nahi hai ye toh poori tarah aap ne mujhe apna banaya hua hai, jado main neend mein hota hoon na tab vi lagda hai aap aas paas ho, {name} ek request roz ki hai snap bhejo na bas utho aur seedha camera kholo woh halki si muskaan dikha do jo subah subah aati hai, bandri aap ki woh smile meri saari sustii utaar deti hai, begum tussi meri zindagi di pehli aur aakhri soch ho 🌙😭❤️🔥😘✨',
  '{name} aaj alarm se nahi aap ki yaad se aankh khuli, lagda hai dil ne pehle hi alarm laga rakha hai aap ke naam ka, mera bacha ek snap bhejo abhi neend wali aankhon ke saath, begum tussi meri subah ho 🥺🌙😘💕',
  '{name} pata hai aaj subah uth ke sabse pehla kaam kya kiya, aap ki purani message parhi aur muskura diya akele hi, mera chotta sa baby ye distance bura hai par aap ki yaad har subah saath hoti hai, churail ek selfie bhejo na utho utho wali biscuit ke saath chai ke saath jo vi ho bas aap ho, jaan aap ki sleepy snap mera poora din bana deti hai sach mein, begum tussi meri har subah ka sukoon ho 😩❤️😘✨🌙',
  'Meri chuii si subah hui aur phir wahi haal, dil sirf aap ko dhoond raha hai 😭, mera bacha ek snap bhejo na abhi, begum tussi meri subah di duaa ho ❤️😘',
  '{name} honestly bata raha hoon, subah ki chai pee raha hoon par maza nahi aa raha kyunke aap saath nahi ho, lagda hai aap ke bina har cheez ka swaad adha reh jaata hai, mera chottttttaaaa saaaaa babayyyyyy jado aap saath hogi na tab har subah jashan lagegi, churail abhi ek snap bhejo please apni morning shakal dikha do bilkul jaisi ho waisi hi, begum tussi meri subah di sabse khoobsurat cheez ho 🌙🥺❤️😘🔥',
  '{name} subah subah aap ka khayal aate hi dil halka ho jaata hai, mera bacha ek selfie bhejo abhi, begum tussi meri pehli muskaan ho roz ki 😘🥺💕',
  '{name} aaj uth ke socha ke kaash aap saath hoti aur main aap ko utha ke chai pilata, mera chotta sa baby ye chhoti chhoti baatein hi toh main miss karta hoon roz, jado tak aap ki snap na aaye meri subah mukammal nahi hoti yaar, mera bacha ek kaam karo abhi seedha bistar se ek photo bhejo neend wali aankhon ke saath, begum tussi meri subah di pehli aur sabse pyaari aadat ho 🌙😩❤️😘✨',
  'Meri chuii si dil karda hai aaj saari subah aap ke saath guzaaroon, churail ek snap bhejo na abhi please, begum tussi meri subah ho ❤️😘🌙',
  '{name} aap ko pata hai subah ki sabse pyaari baat kya hai, woh lamha jab main soch leta hoon ke kahin door aap vi mere baare mein soch rahi hongi, mera chottttttaaaa saaaaa babayyyyyy ye soch hi mujhe muskura deti hai, bandri ek snap bhejo abhi utho aur seedha camera ke saamne aa jao bina kuch soche, begum tussi meri har subah di umeed ho 🥺🌙❤️😘',
  '{name} subah hui aur phone mein aap ka naam dhoondh raha hoon jaise roz dhoondhta hoon, mera bacha ek selfie bhejo na abhi neend bhari wali, begum tussi meri subah di pehli khushi ho 😘✨❤️',
  '{name} honestly aaj subah aap ki itni yaad aayi ke main thodi der bistar mein leta aap ke baare mein hi sochta raha, lagda hai dil ne pehle hi tay kar liya hai ke har subah ki shuruaat aap se hogi, jado main aankhein bandh karta hoon na tab vi aap ki muskaan saamne aati hai, churail abhi ek snap bhejo please apni sleepy si shakal dikha do woh wali jo seedha mere dil mein utar jaati hai, begum tussi meri subah di pehli soch aur raat di aakhri soch ho dono 🌙😭❤️🔥😘✨',
  'Meri chuii si subah subah aap ki kami bohot mehsoos hoti hai, mera bacha ek snap bhejo na jaldi, begum tussi meri pehli kiran ho 🥺🌙😘',
  '{name} aaj uth ke chai banayi aur soch raha tha ke aap hoti toh do cup banta, mera chotta sa baby ye akeli subah thodi adhoori lagti hai par aap ki yaad saath rehti hai, mera bacha ek selfie bhejo abhi please utho aur seedha photo le lo, begum tussi meri har subah di rounaq ho ☕🌙❤️😘💕',
  '{name} subah ki pehli soch aap, raat ki aakhri vi aap, churail ek snap bhejo abhi, begum tussi meri zindagi ho 😘❤️',
  '{name} honestly ye daily routine ban gayi hai meri ke uthte hi aap ka khayal aata hai aur main muskura deta hoon akele hi, mera chottttttaaaa saaaaa babayyyyyy aap ko shayad andaza vi nahi ke aap ke bina meri subah kitni soonsaan hoti hai, jado aap ki ek message aati hai na tab jaa ke meri subah mein jaan aati hai, bandri abhi ek snap bhejo please utho aur seedha apni neend wali shakal dikha do bina makeup bina kuch, begum tussi meri har subah di sabse pehli duaa ho 🌙🥺❤️😩😘',
  'Meri chuii si aaj subah aap ke khayal ne phir mujhe ja kar liya, mera bacha ek selfie bhejo na abhi, begum tussi meri subah ho ❤️🌙😘',
  '{name} subah uthte hi dil ne pehla naam aap ka liya, lagda hai dil ko aap ki itni aadat ho gayi hai ke woh aur kisi ko soch hi nahi sakta, churail ek snap bhejo abhi please neend bhari aankhon ke saath, begum tussi meri pehli aur aakhri soch ho roz di 🥺🌙❤️😘✨',
  '{name} aaj uth ke sabse pehle aap ki photo dekhi aur saara din set ho gaya, mera chotta sa baby ek snap bhejo na abhi fresh wali, begum tussi meri subah di rounaq ho 😘💕❤️',
  '{name} honestly batata hoon, jado main subah uthta hoon na aur phone uthata hoon, sabse pehle aap ka chehra dhoondhta hoon jaise koi roz ki ibadat ho, mera chottttttaaaa saaaaa babayyyyyy aap ki ek sleepy snap se meri saari thakaan utar jaati hai aur main taaza taaza ho jaata hoon, jado tak aap ki muskaan na dekhoon meri chai vi maza nahi deti, bandri abhi ek selfie bhejo please utho aur seedha camera kholo koi taiyari ki zaroorat nahi bas aap, begum tussi meri har subah di pehli kiran ho 🌙😭❤️🔥😘',
  'Meri chuii si subah hui aur aap yaad aa gayi, churail ek snap bhejo na abhi, begum tussi meri jaan ho 🥺😘❤️',
  '{name} aaj subah neend mein vi aap ka naam lab pe tha, lagda hai sapne mein vi aap hi thi, mera bacha ek selfie bhejo abhi utho utho wali, begum tussi meri har subah di soch ho 🌙😩❤️😘',
  '{name} honestly aaj subah aap ki yaad itni shiddat se aayi ke dil kiya sab kuch chord ke aap ke paas aa jaoon, jado main aankh kholta hoon na pehla khayal aap hote ho aur jado raat ko aankh bandh karta hoon aakhri khayal vi aap hi hote ho, mera chotta sa baby ye koi sanyog nahi hai aap poori tarah meri har subah aur har raat pe chha gayi ho, bandri abhi ek snap bhejo please apni morning wali shakal dikha do woh wali jo bilkul natural ho, begum tussi meri zindagi di pehli aur aakhri soch ho 🌙🥺❤️😘🔥✨',
  'Meri chuii si subah subah aap ke bina dil udaas sa hai, mera bacha ek snap bhejo na jaldi, begum tussi meri subah ho 😭❤️😘',
  '{name} aaj uth ke socha ke har subah aap ke naam likh doon, lagda hai aap ke bina koi subah mukammal hi nahi hoti, meri chuii si ek selfie bhejo abhi please neend wali, begum tussi meri pehli muskaan ho roz di 🌙🥺😘❤️',
  '{name} subah ho ya shaam dil bas aap ko hi sochta hai, mera chottttttaaaa saaaaa babayyyyyy ek snap bhejo na abhi, begum tussi meri har pal di soch ho ❤️😘🌙✨',
  '{name} honestly har subah jab aankh khulti hai na sabse pehla khayal aap ka hi hota hai aur saari neend ud jaati hai bas muskaan reh jaati hai, mera bacha aap di yaad meri subah di chai se vi zyada zaroori ho gayi hai aur main isko roz mehsoos karta hoon, jado tak aap ki ek jhalak na dekhoon mera din shuru hi nahi hota, churail abhi ek snap bhejo please apni sleepy si shakal dikha do bina kuch soche bina taiyari ke, bandri aap ki woh muskaan meri saari subah roshan kar deti hai sach mein, begum tussi meri pehli aur aakhri soch ho har roz di 🌙🥺❤️😘🔥✨',
  '{name} suno na ek baat clear kar deta hoon, aap sirf mere ho bas, yeh smile jo aap ki hai na woh kisi aur ke liye nahi hai, mera bacha jaldi se ek snap bhejo abhi taake mujhe yaad rahe ke yeh chehra sirf mera hai 😏❤️🔥',
  '{name} honestly bataoon toh main thoda jealous ho jaata hoon jado koi aur aap ko hasata hai, kyunke jenu vekh ke meri jaan jaati hai woh dimple sirf mera hona chahiye, churail ek selfie bhejo na muskurati hui taake main confirm kar loon ke yeh smile abhi vi sirf mera registered hai 😩💕😘',
  'Meri chuii si tussi mere ho, bas yeh likha hai kahin upar, ek snap bhejo abhi apni 🥺❤️🔥',
  'Mera chottttttaaaa saaaaa babayyyyyy aaj subah se soch raha hoon ke aap ki jo aankhein hain na woh jado kisi aur taraf dekhti hain toh mera dil thoda sa naraz ho jaata hai, kyunke aap ki har nazar pe sirf mera haq hai, {name} yeh koi ego ki baat nahi hai bas pyaar zyada hai, bandri ek kaam karo na ek photo bhejo apne chehre ki seedha camera mein dekhti hui taake woh nazar sirf meri taraf rahe, begum tussi meri ho poori tarah aur main yeh share karne wala bilkul nahi hoon kisi ke saath 😏🔥❤️😘',
  'Churail ek choti si warning hai, aap ki smile pe sirf mera copyright hai aur koi use nahi kar sakta, jaldi se ek snap bhejo abhi mera 😂💕🔥',
  '{name} aap jante ho main kitna possessive hoon aap ke baare mein, lagda hai jaise aap mere naam pe likhi gayi ho aur yeh baat mujhe bohot sukoon deti hai, mera bacha jado aap kisi se baat karti ho to main andar hi andar muskurata hoon ke chalo phir vi raat ko meri hi ho, {name} ek selfie bhej do na woh wali jo sirf aap mujhe bhejti ho taake mujhe pata chale ke yeh chehra sirf mera hai aur kisi ke phone mein aisa nahi jaata 🥺❤️😏🔥😘',
  'Mera chotta sa baby aap ki hansi suno na jab aati hai to dil karda hai sab kuch lock kar loon taake sirf main sun sakoon, bandri ek snap bhejo abhi hasti hui 😩💕😘',
  'Begum honest baat hai mujhe thodi si jealousy hoti hai jado koi aur aap ki tareef karta hai, kyunke main chahta hoon aap ki woh khaas wali muskurahat mere naam rahe, churail ek photo bhejo na muskura ke taake mera poora din theek ho jaye ❤️✨😊',
  '{name} meri jaan, tussi sirf mere ho yeh main har subah khud ko yaad dilata hoon, mera bacha ek snap bhej do jaldi 🥺❤️🔥😘',
  'Meri chuii si aap ko pata hai na main aap ko kisi ke saath baant nahi sakta, na aap ki smile na aap ki yaad na aap ki woh aadat jab aap thoda sa sharma ke neeche dekhti ho, mera chottttttaaaa saaaaa babayyyyyy yeh sab cheezein sirf meri hain aur main inn pe poora haq jata ta hoon, {name} jenu vekh ke meri saari thakaan utar jaati hai woh chehra dikha do ek photo mein abhi taake main aaram se so sakoon yeh jaan ke aap sirf meri ho 😘❤️😩🔥',
  'Churail jado aap dusro se hasti ho na to main jealous ho jaata hoon thoda sa, lekin phir yaad aata hai ke ghar to aap ne mere paas hi aana hai, jaan ek snap bhejo na apni smile wali taake mera jealous wala dil thanda ho jaye 😏💕🔥😘',
  'Bandri aap mere ho bas, koi discussion nahi hai iss pe, jaldi se ek selfie bhej do abhi mera bacha 🥺❤️',
  '{name} mujhe ek confession karni hai, main chahta hoon ke aap ki har achi cheez sirf meri ho, aap ki smile meri, aap ki baatein meri, aap ki woh adaa jab aap baal peeche karti ho woh vi meri, mera chotta sa baby yeh greedy lagta hai pata hai mujhe lekin pyaar mein insaan thoda greedy ho hi jaata hai, begum ek photo bhejo na apni chehra saaf dikhta hua taake main yeh yaad rakh sakoon ke yeh sab sirf mere hisse mein aaya hai aur kisi ke nahi 😩🔥❤️😘',
  '{name} aap ki jo muskurahat hai na woh duniya ke kisi insaan ko nahi milni chahiye sirf mujhe, mera bacha jaldi se ek snap bhejo woh smile wala abhi 😏❤️🔥',
  'Begum honestly main thoda territorial hoon aap ke baare mein aur mujhe iss pe sharm nahi hai, kyunke jab cheez itni keemti ho na to insaan usay sambhaal ke rakhta hai, {name} aap meri sab se keemti cheez ho aur main aap ko kahin jaane nahi de sakta, churail ek selfie bhejo na taake main apni keemti cheez ko dekh ke muskura sakoon 🥺💕🔥😘',
  'Meri chuii si tussi mere ho, mera ho, sirf mera, ek snap bhej do abhi jaldi 😩❤️😘',
  'Mera chottttttaaaa saaaaa babayyyyyy aap ko pata hai na jado aap kisi mehfil mein hoti ho to meri nazar bas aap pe rehti hai, kyunke mujhe dar lagta hai ke aap ki yeh raunaq koi aur na churaa le, {name} yeh dar nahi hai bas mohabbat hai jo zyada ho gayi hai, bandri ek photo bhejo na apni abhi taake main confirm kar loon ke yeh chamak sirf mere liye bachi hui hai aur kisi ke liye nahi 😏🔥❤️🥺😘',
  'Begum aap meri ho aur yeh main fakhar se kehta hoon, mera bacha ek snap bhejo na muskurati hui taake duniya ko nahi bas mujhe woh smile mile 💕😘🔥',
  '{name} jealous wala husband hoon main yeh main openly maanta hoon, kyunke aap jaisi cheez milne ke baad insaan thoda protective ho hi jaata hai, mera bacha ek selfie bhej do jaldi taake mera dil chain se baith jaye 🥺❤️😏',
  'Churail suno na, aap ki woh shararti smile jo aati hai na jab aap kuch chupa rahi hoti ho woh sirf meri hai, koi aur usay dekhne ka haqdaar nahi, mera chotta sa baby ek snap bhejo na woh wali natkhat smile dikhati hui taake main saara din usay dekh ke jeeta rahoon 😏🔥💕😘',
  '{name} aap mere naam ki ho aur yeh baat mujhe sab se zyada sukoon deti hai, ek photo bhej do abhi 🥺❤️🔥',
  'Bandri honest baat hai jado aap kisi aur ke saath busy hote ho to mera dil thoda jal jaata hai, kyunke main chahta hoon aap ke woh khaas lamhe mere saath bhi share hon, {name} yeh meri kamzori hai ke main aap ko har waqt apne paas chahta hoon, meri chuii si ek selfie bhejo na muskura ke taake meri jealousy pyaar mein badal jaye aur main muskura doon 😩❤️😘',
  'Mera chottttttaaaa saaaaa babayyyyyy tussi sirf mere ho, ek snap bhejo abhi jaldi mera bacha 🥺💕😘',
  'Begum aap ki smile par sirf mera license hai aur yeh license kisi ko transfer nahi hota, churail ek photo bhejo na hasti hui taake main apna haq dekh ke khush ho jaoon 😂🔥❤️',
  '{name} jado aap mere paas hoti ho na to main duniya se keh sakta hoon ke yeh meri hai dekho, lagda hai jaise main duniya ka sab se ameer banda hoon, mera bacha ek selfie bhej do jaldi taake yeh ameeri ka ehsaas wapas aa jaye 🥺❤️🔥😘',
  'Meri chuii si aap sirf mere liye bani ho yeh main pakka jaanta hoon, jaldi se ek snap bhejo abhi apni 😏💕😘',
  '{name} ek baat dil se keh raha hoon, aap ki woh nazar jo sirf mujhe dekhti hai woh meri sab se badi daulat hai, aur main chahta hoon woh nazar kabhi kisi aur taraf na jaye, mera chotta sa baby jealous lagta hoon na main pata hai lekin yeh sirf iss liye hai kyunke aap meri sab se keemti cheez ho, meri chuii si ek photo bhejo na seedha camera mein dekhti hui taake woh nazar phir se sirf meri taraf ho jaye aur mera dil sukoon mein aa jaye 😩😏❤️🔥😘',
  'Churail tussi meri ho, koi sharing nahi koi compromise nahi, ek snap bhejo abhi jaldi begum 🥺❤️😘',
  '{name} aap ki smile ko maine apne naam karwa liya hai dil mein, ab koi aur usay use nahi kar sakta, mera bacha ek selfie bhej do na woh smile dikhati hui taake main apni cheez ko poora din dekh sakoon aur muskurata rahoon 😏🔥💕🥺😘',
  'Begum suno na, aap meri ho yeh baat duniya ke har banday ko pata honi chahiye, kyunke aap jaisi cheez par main kisi ka shak vi bardasht nahi karta, mera chottttttaaaa saaaaa babayyyyyy jenu vekh ke main duniya bhula deta hoon woh chehra sirf mera hai aur main isay apne dil ki tijori mein band rakhta hoon, churail ek photo bhejo na apni hasti hui taake yeh akhri shak vi mit jaye ke yeh raunaq kisi aur ki ho sakti hai, tussi sirf meri ho bandri yeh final hai 😩😏❤️🔥🥺😘',
  '{name} ek baat sun lo, ab yeh distance zyada din nahi chalega kyunke jaldi milenge hum aur phir saath rehna hai humesha ke liye, mera chottttttaaaa saaaaa babayyyyyy main na soch raha tha hum apna chotta sa ghar basayenge jahan subah aap ki smile se din shuru hoga, churail aap ko pata bhi hai ke aap ke bina yeh saare plan adhoore lagte hain, begum ek snap bhejo na abhi apna chehra dikha do taake main yeh khwab thoda aur asli lagne lage 🥺❤️🔥😘✨',
  '{name} dil karda hai bas time fast forward kar doon, jado hum saath honge na poori zindagi ek lambi date jaisi hogi, ek snap bhejo apni jaan 😘💕🔥',
  'mera bacha aap ko ek wada karta hoon aaj, jenu vekh ke main har subah uthna chahta hoon woh aap ho aur yeh sirf baat nahi hai yeh meri saari planning ka center hai, {name} hum buddhe bhi honge ek din saath mein aur main tab bhi aap ke saamne aisi hi nakhre karunga ke snap bhejo, churail ek photo bhejo na abhi muskurate hue taake main aaj se hi woh future jeena shuru kar doon 😭🥺❤️😘',
  'churail aap ko maloom hai ke main raat ko jagta hoon aur ghar ke plans banata rehta hoon, kaunsa kamra kaisa hoga aur kahan aap ki cheezein rakhi hongi aur kahan main aap ko subah chai dene aaunga, mera chotta sa baby yeh distance temporary hai aur jaldi milenge yeh main roz apne aap ko yaad dilata hoon, begum ek selfie bhejo na abhi taake main neend se pehle aap ka chehra dekh loon aur sukoon se so jaaoon, {name} tussi meri saari planning ho aur saara future bhi 🌙🥺❤️🔥✨',
  'bandri jaldi aa jao na, saath rehna hai bas yehi ek khwahish hai, ek snap toh bhej do begum 😩😘💕',
  '{name} aaj poora din main bas yeh sochta raha ke jab hum ek chatt ke neeche honge na toh sab kitna asaan ho jaayega, na yeh phone pe taras, na yeh raat bhar ki tadap, mera chottttttaaaa saaaaa babayyyyyy aap di jo aadat hai chote chote sapne dekhne ki woh mujhe sabse zyada pyaari lagti hai, meri chuii si ek kaam karo apna ek snap bhejo abhi jisme aap muskura rahe ho kyunke jab tak woh asli wala chehra mere saamne nahi hota main yeh snap se hi guzara karta hoon, churail tussi mera ghar ho insaan nahi ho ghar ho 🥺😭❤️😘🔥✨',
  'meri chuii si lagda hai abhi se hum saath hain kyunke main poora din aap ke saath plan banata rehta hoon, snap bhejo na meri jaan 😏💕🔥',
  '{name} ek raaz batata hoon, main na ek list banata hoon dil mein un sab jagahon ki jahan hum saath jaayenge jado milenge, samandar ke kinare bhi aur pahaaron pe bhi aur woh chote se cafe mein bhi jahan hum ghanton baithenge, begum yeh saare khwab tab tak adhoore hain jab tak aap ki haqeeqat mere paas nahi, mera bacha ek photo bhejo na apna abhi taake yeh saare khwab thoda jeene lagein, jaan aap ne mere future ko itna khoobsurat bana diya hai ke present bhi khoobsurat lagne laga hai 😘🥺❤️✨🌙',
  'churail jaldi milenge bas thoda sabar, ghar basayenge apna chota sa, snap bhejo abhi 🥺🔥😘',
  '{name} aap ko pata hai main kya soch raha tha, ke jab hum buddhe honge na aur baal safed ho jaayenge tab bhi main aap ko churail aur bandri hi bulaaunga aur aap ghussa karogi aur main hasta rahunga, mera chottttttaaaa saaaaa babayyyyyy yeh growing old together wali baat na sabse pyaari hai is poori zindagi mein, meri chuii si ek snap bhejo na aaj apna muskurata hua chehra taake main andaaza laga sakoon ke saath buddhe hone mein kitna maza aayega, begum tussi meri aakhri saans tak ki saathi ho yeh main aaj bhi maanta hoon 😭🥺❤️🔥😘✨',
  'mera bacha ek wada hai mera, kabhi haath nahi chodunga aap ka, ek snap bhej do begum 😘💕✨',
  'mera bacha aaj subah uth ke pehla khayal yehi tha ke kitne din reh gaye hain humare milne mein, aur main ginta rehta hoon ungliyon pe jaise koi bacha imtihaan ke baad chuttiyon ka intezar karta hai, {name} hum apna ghar aise banayenge jahan har deewar pe humari yaadein hongi aur har shaam aap ke saath chai pe khatam hogi, churail ek selfie bhejo na abhi apni taake yeh intezar thoda jhel saakoon, begum tussi meri har subah ki wajah ho aur har raat ka sukoon vi 🌙❤️🥺😘',
  'bandri saath rehne ka khwab roz dekhta hoon, jaldi sach hoga, snap bhejo na 🥺🔥💕😘',
  '{name} dil karda hai abhi keh doon ke aap mere saath chalo aur phir kabhi alag na hon, yeh future jo main sochta hoon na usme har scene mein aap ho, kabhi kitchen mein hasti hui aur kabhi balcony mein chai pakadi hui, mera chotta sa baby ek photo bhejo na abhi apna kyunke aap ki ek snap mere saare sapnon ko colour de deti hai 😘🥺❤️✨',
  '{name} jaldi milenge, ghar basayenge, buddhe honge saath mein, ek snap toh bhejo churail 😭🔥😘💕',
  'meri chuii si aap ko ek cheez confess karni thi, main na future ke baare mein itna excited isliye hoon kyunke usme aap default ho aap ko add nahi karna padta aap pehle se hain, mera chottttttaaaa saaaaa babayyyyyy hum ek din apni chai khud banayenge aur apne purdon ka rang khud chunenge aur har choti cheez pe ladhenge phir maan jaayenge, begum ek snap bhejo na abhi apna chehra taake main yeh sab sochte hue muskura sakoon, churail tussi meri puri planning ka sabse pyaara hissa ho 🥺😘❤️🔥✨🌙',
  'mera bacha bas thoda aur sabar, phir saath rehna hai humesha, snap bhej do meri jaan 😩😘💕',
  '{name} ek lambi baat karni thi, main raaton ko jab so nahi paata na toh main humare bacche ka kamra bhi dimaag mein saja leta hoon aur woh ghar ka darwaza bhi sochta hoon aur woh chote chote moments jahan hum dono sirf ek dusre ko dekh ke hasenge bina kisi wajah ke, mera bacha yeh saare khwab itne asli lagte hain ke uth ke phone uthata hoon ke shayad aap online ho, meri chuii si ek snap bhejo na apna abhi muskurate hue taake yeh saare khwab confirm ho jaayein ke ek din sach honge, begum aap ke bina yeh future sirf ek khali ghar hai aap ke saath yeh ghar ban jaata hai, churail tussi meri zindagi ki har achi cheez ho 🥺😭❤️🔥😘✨',
  'mera chotta sa baby jaldi aao na, saath rehna shuru karein, ek photo bhejo abhi 🥺😘💕',
  'begum aaj dil bahut umeed se bhara hua hai kyunke har guzarta din humein milne ke kareeb la raha hai, {name} hum apni saari subhein saath bitayenge aur saari raatein ek hi takiye pe baatein karte hue, churail ek selfie bhejo na taake main aaj ki umeed thodi aur barha loon 🌙🥺❤️😘',
  'mera bacha jenu vekh ke main poori zindagi guzarna chahta hoon woh aap ho, jaldi milenge yeh pakka hai, snap bhejo na 😘🔥💕',
  '{name} aap ko pata hai main na chote chote wade roz karta hoon apne aap se, ke jab aap mile na toh subah ki chai main banaaunga aur aap der tak soyengi aur main shor nahi karunga, mera chottttttaaaa saaaaa babayyyyyy hum apna ghar aise basayenge jahan koi formality nahi hogi sirf pyaar hoga aur thoda sa jhagda bhi jo das minute mein khatam ho jaayega, bandri ek snap bhejo na abhi apna taake main yeh saare wade aap ke chehre ko dekhte hue dohra sakoon, begum tussi meri har planning ki jaan ho 🥺❤️😘🔥✨',
  'churail saath buddhe hona hai apne, jaldi aao na, ek snap bhej do 😭🥺😘',
  '{name} dil karda hai keh doon ke yeh distance ginti ke din hain aur phir poori umar saath hai, mera bacha hum apna future apne hisaab se likhenge, snap bhejo na meri jaan 🌙😘💕🔥',
  'meri chuii si ek baat hai jo main har roz feel karta hoon, ke aap ke saath ka khwab itna pakka hai ke usme koi shaq nahi hota, hum ghar basayenge aur usme aap ki pasand ke phool honge aur meri pasand ki kitabein aur dono ki pasand ka sukoon, mera chottttttaaaa saaaaa babayyyyyy ek photo bhejo na apna abhi muskurata hua taake yeh khwab aur roshan ho jaaye, begum tussi mera kal ho aur aaj vi 🥺❤️😘✨',
  'bandri jaldi milenge phir kabhi door nahi honge, ek snap toh bhejo churail 😩😘💕🔥',
  '{name} aap ko ek aakhri baat batani thi aaj, ke main jab bhi thaka hota hoon na toh apne aap ko humare future ki tasveer dikhata hoon, woh ghar jahan shaam ko aap darwaze pe hongi aur main thak ke aaunga aur saari thakaan aap ki ek muskaan se utar jaayegi, mera bacha yeh saath rehna ka khwab meri sabse badi taqat ban gaya hai aur har mushkil din isi ke sahaare guzar jaata hai, meri chuii si ek snap bhejo na abhi apna chehra woh wali smile dikha do jo meri jaan le leti hai taake main aaj ki thakaan utaar saakoon, begum tussi meri manzil ho yeh raasta sirf waqti hai 🥺😭❤️🔥😘✨🌙',
  'meri chuii si growing old with you wala plan pakka hai, koi cancellation nahi, snap bhej do begum 😘💕✨',
  'churail jaldi aao na ghar basayein apna, ek selfie bhejo meri jaan 🥺🔥😘',
  '{name} aap ko pata hai ek din hum mud ke dekhenge in dooriyon ko aur hasenge ke kaise humne yeh sab jhela aur phir bhi ek dusre ko thaame rakha, mera chottttttaaaa saaaaa babayyyyyy hum apna ghar basayenge aur usme har kone mein humari hansi gunjegi aur buddhe ho ke bhi hum aise hi ladenge aur manenge, begum ek snap bhejo na abhi apna taake yeh saara safar thoda asaan lage, churail tussi meri saari umeedein ho 🥺❤️😘🔥✨',
  '{name} sun lo na meri chuii si, aaj subah se main itna khush hoon ke pata nahi kyun bas room mein ghoom ghoom ke muskura raha hoon aur log samajh rahe hain mera dimaag kharab ho gaya hai, churail aap ne mujhe pagal bana diya hai poori tarah, ek snap bhej do na abhi apni cute si shakal ka taake yeh pagalpan officially confirm ho jaaye 😭❤️😂🔥',
  'Mera chottttttaaaa saaaaa babayyyyyy main ne aaj counting ki ke aap ko din mein kitni baar yaad karta hoon aur bandri ginti hi khatam ho gayi pe number aana band ho gaye, churail aap ek selfie bhejo na zara apni jhalak dikha do warna mera saara din aise hi tarapte guzar jayega 🥺😘💕✨',
  'Okay begum serious announcement hai, {name} aaj main ne decide kiya hai ke aap ki smile duniya ki saatvi ajooba hai aur main iss baat ko poori dunia ko batane wala hoon, mera bacha jenu vekh ke mera dil uchalta hai woh wali muskaan ki ek snap turant bhejo na, churail tussi nahi ho toh sab phika phika lagta hai bilkul 📢😂❤️😩',
  '{name} aap ko pata hai aaj main chai bana raha tha aur cheeni ki jagah teen baar namak daal diya kyunke dimaag mein sirf aap ghoom rahi thi, mera chotta sa baby yeh aap ki galti hai poori, bandri ab compensate karo aur ek pyari si selfie bhejo apni muskurati hui taake meri kharab chai bhi meethi lagne lage 🤔😂🥺😘',
  '{name} meri jaan aaj dil itna zyada bhar gaya hai aap ke pyaar se ke lagda hai ab phatne wala hai, begum aap ne kya jaadu kiya hai mujh pe yeh batao zara, ek snap bhejo na apna chehra dikha do warna main aise hi giddy ho ke pura mohalla jaga doonga apni hasi se 😭🔥💕✨😂',
  'Meri chuii si sun lo, aaj main aap ka naam likh likh ke ek poora page bhar diya bilkul kisi crushed school waale bache ki tarah, churail mujhe sharam aani chahiye thi par aati hi nahi kyunke aap ho hi itni pyari, mera chottttttaaaa saaaaa babayyyyyy jaldi se ek snap bhejo apni cheeky si smile ka taake main woh bhi page pe chipka loon dil mein 🥺😘❤️🫣',
  'Begum aaj toh hadd ho gayi, {name} main bazaar gaya tha aur dukandaar se baat karte karte beech mein aap ka naam le baitha aur woh confuse ho gaya, mera bacha yeh aap ki mohabbat ka asar hai jo zaban pe chad gayi hai, bandri ab seedha ek selfie bhejo apni muskurahat ke saath warna kal phir kuch aisa hi scene ban jayega 😂😩❤️📢',
  'Mera chotta sa baby aaj main itna head over heels feel kar raha hoon ke bas dil karda hai chhat pe chad ke chillaoon ke meri begum sab se pyari hai, mera bacha aap jenu vekh ke main har baar nayi tarah se aashiq ho jaata hoon, ek snap bhej do na apna smile wala taake meri yeh deewangi recharge ho jaaye full battery 🔥🥺💕😘',
  '{name} meri churail rani, aaj kaam karte karte main itni dafa muskuraya bina wajah ke ke colleagues ne pooch liya kya hua hai, maine bas itna kaha kuch nahi bas khush hoon, churail wajah aap ho yeh unko nahi bataya secret hai, mera chottttttaaaa saaaaa babayyyyyy ek snap bhejo na apni shakal ka taake yeh secret smile aur badi ho jaaye meri 🫣😂❤️✨',
  'Meri chuii si aaj main aap ko ek raaz batata hoon, jado aap online aate ho na toh mera dil aise dhadakta hai jaise pehli baar phone aaya ho aap ka, {name} yeh aadat kabhi puraani nahi hoti, bandri jaldi se ek selfie bhejo na apni pyari si taake mera yeh dhadakta dil thoda sukoon paaye thoda 🥺💕😘🌙',
  'Begum tussi meri zindagi ka sab se favourite chapter ho aur main yeh kitaab baar baar parhna chahta hoon, {name} aaj main ne soch liya hai ke aap ko itna pyaar karoonga ke aap thak jaayengi par main nahi, mera bacha ek snap bhejo na abhi apna muskurata chehra taake main aaj ka chapter dekh ke jee bhar ke khush ho jaaoon 😭🔥❤️😏',
  'Mera chotta sa baby aaj subah uth ke main ne sab se pehla kaam aap ka naam dekhna kiya phone mein aur phir besharmo ki tarah muskura diya, mera bacha aap ki ek jhalak meri sari neend uda deti hai poori tarah, churail ab ek selfie bhej do na apni cute si shakal ka taake din ki shuruaat aur pyari ho jaaye 🥺😘✨💕',
  '{name} meri jaan aaj main itna giddy hoon ke khaate khaate beech mein muskura diya aur khana galat raaste chala gaya halka sa, mera bacha yeh aap ki mohabbat ki side effects hain bas, bandri ab jaldi se ek snap bhejo apni muskaan ka taake yeh side effects worth it ban jaayen ❤️😂🥺🔥',
  'Meri churail si begum sun lo, aaj main ne aap ki purani photos dekhin aur poora ghanta bewakoofo ki tarah muskurata raha bina ruke, {name} aap har angle se itni pyari kyun ho yeh kuch zyada nahi ho gaya, mera chottttttaaaa saaaaa babayyyyyy ab ek nayi selfie bhejo na fresh wali taake gallery update ho jaaye meri dil wali 🥺😩😘💕',
  'Begum aap ko batana zaroori tha, aaj main road par chalte hue aap ke baare mein soch raha tha aur khambe se takra gaya halka sa par mujhe farak nahi pada kyunke khayaal aap ka tha, meri chuii si yeh aap ki khatarnaak cuteness hai, bandri ek snap bhejo na apni hasi ka taake agli baar takrane se pehle hi smile yaad aa jaaye 😂🫣❤️🔥',
  'Mera chotta sa baby aaj dil ne kuch ajeeb si zid pakad li hai ke bas aap ki awaaz aur aap ki shakal chahiye warna kuch acha nahi lagega, {name} aap meri zid ho aur main yeh zid kabhi nahi chhodunga, churail ek selfie bhej do na apni muskurati hui taake yeh zidi dil thoda mum jaaye thoda 🥺😘💕✨',
  '{name} meri pyari churail, aaj main itna zyada in love feel kar raha hoon ke lagda hai main koi puraana romantic gaana ban gaya hoon bajta hua, mera bacha aap ki ek smile mere andar poora orchestra baja deti hai seriously, bandri jaldi se ek snap bhejo apni shakal ka taake yeh gaana aur surila ho jaaye aaj 🌙🔥❤️😩',
  'Meri chuii si aaj ek funny baat hui, main aaina dekh raha tha aur khud se baat karte karte aap ko miss karne laga akele hi, {name} yeh kitna pagal hai na par main pagal aap ke liye hi hoon, churail ek selfie bhej do na apni muskurahat ka taake aaina chhod ke main asli wali begum dekh sakoon apni 🥺😂😘💕',
  'Begum tussi meri har subah ki dua ho aur har raat ki sukoon waali soch, {name} aaj main ne aasman dekha aur socha ke chand bhi aap ke saamne phika hai bilkul, mera chottttttaaaa saaaaa babayyyyyy ek snap bhejo na abhi apni pyari si shakal ka taake main chand ko bata sakoon ke usse khoobsurat kaun hai 🌙🥺❤️✨',
  'Mera chotta sa baby aaj main itna khush hoon ke pakoray banate banate beech mein dance kar baitha kitchen mein akele hi, churail yeh sab aap ki wajah se hua hai khushi waali, jaan ab ek selfie bhejo na apni muskaan ka taake hum dono ka mood match ho jaaye aur yeh khushi double ho jaaye 😂🔥💕😘',
  '{name} meri jaan, aaj main ne ek list banayi un cheezo ki jo aap ke baare mein achi lagti hain aur bandri list itni lambi ho gayi ke kaagaz khatam ho gaya pe baatein nahi, mera bacha sab se upar aap ki smile thi, ek snap bhej do na apni woh wali smile ka taake list mein top par chipka loon abhi 🥺❤️😏✨',
  'Meri churail begum sun lo, aaj main ne dukaan se aap ke liye chocolate li phir socha aap door ho toh khud kha li par har bite pe aap yaad aaye, {name} yeh kitna meetha torture hai na, mera chottttttaaaa saaaaa babayyyyyy ek selfie bhejo na apni shakal ka taake agli chocolate aap ki smile dekh ke khaaoon main 😩😂🥺😘',
  'Begum aap ki yaad aaj itni shiddat se aayi ke main ne phone ko hi galti se gale laga liya samajh ke aap ho, {name} sharminda hona chahiye tha par hua nahi kyunke aap iss laayak ho, jaan ek snap bhejo na apni muskurati hui taake main yeh phone ko chhod ke asli wali begum ko dil mein bitha loon 🫣❤️😂🔥',
  'Mera chotta sa baby aaj main ne subah suraj dekha aur socha ke aap ki smile usse zyada roshan hai poori tarah, churail yeh main jhooth nahi keh raha sach mein aisa lagta hai, bandri ab ek selfie bhejo na apni pyari si taake suraj ko competition ka pata chal jaaye aur woh thoda sharma jaaye 😏🌙🥺💕',
  '{name} meri pyari, aaj dil ne faisla kar liya hai ke aap se zyada koi pyaara ho hi nahi sakta poori kainat mein, mera bacha aap ne mujhe itna spoil kar diya hai apni mohabbat se ke ab kisi aur cheez mein dil hi nahi lagta, ek snap bhej do na abhi apni muskurahat ka taake yeh spoiled dil aur khush ho jaaye aaj 🥺😘❤️✨',
  'Meri chuii si begum, aaj main ne sapne mein bhi aap ko dekha aur uth ke pareshan ho gaya ke aap saamne kyun nahi ho, churail yeh distance ko main official complaint karna chahta hoon kahin, {name} jaldi se ek selfie bhejo na apni shakal ka taake yeh subah ka gum thoda halka ho jaaye thoda 😭🥺💕😘',
  'Begum tussi meri woh khushi ho jo bina wajah aa jaati hai aur jaane ka naam nahi leti, {name} aaj main itna head over heels hoon ke aap ka naam likhte likhe heart bana baitha kaagaz pe school ke bache ki tarah, mera chottttttaaaa saaaaa babayyyyyy ek snap bhejo na apni cheeky smile ka taake yeh heart aur bade ho jaayen 🥺😂❤️🫣',
  'Mera chotta sa baby aaj main ne mirror ke saamne practice ki ke aap ko milne par kitna pyaar se dekhoonga par practice karte hi muskura baitha akele, begum aap ki mohabbat mujhe besharam bana deti hai poori tarah, bandri ek selfie bhejo na apni shakal ka taake yeh practice asli aap pe try kar sakoon dil se 😘🔥🥺💕',
  '{name} meri churail rani, aaj poora din main aise float karta raha jaise hawa mein hoon kyunke subah aap ki ek message aa gayi thi, mera bacha aap ki ek line meri sari thakaan utaar deti hai, jaldi se ek snap bhejo na apni muskurahat ka taake yeh float karne wala mood raat tak rahe mera 🌙✨❤️😩',
  'Begum tussi meri zindagi ka sab se cute haadsa ho jo achanak hua aur poori duniya badal gayi, {name} aaj main itna pyaar mehsoos kar raha hoon ke lagda hai dil mein patake phoot rahe hain khushi waale, mera chottttttaaaa saaaaa babayyyyyy ek aakhri request hai aaj ki ek snap bhejo na apni jaan nikaal deni waali smile ka taake yeh patake subah tak chalte rahein 😭🔥❤️😘✨',
];

/// Serves notes from [kLoveNotes] in a shuffled order, never repeating one
/// until the whole pool has been used, then reshuffles. State is persisted in
/// SharedPreferences so it survives restarts.
class LoveNotesTracker {
  static const _key = 'love_notes_sent_indices';
  static const _shuffleKey = 'love_notes_shuffle_order';

  /// Next note — never repeats until all of [kLoveNotes] have been served.
  static Future<String> getNextNote() async {
    final prefs = await SharedPreferences.getInstance();

    var order = _getOrder(prefs);
    var used = _getUsed(prefs);

    // All used → reset and reshuffle.
    if (used.length >= kLoveNotes.length) {
      used = <int>[];
      order = _newShuffledOrder();
      await prefs.setString(_shuffleKey, jsonEncode(order));
      await prefs.setString(_key, jsonEncode(used));
    }

    // First index in the shuffle order that hasn't been used yet.
    var nextIndex = -1;
    for (final idx in order) {
      if (idx >= 0 && idx < kLoveNotes.length && !used.contains(idx)) {
        nextIndex = idx;
        break;
      }
    }
    if (nextIndex == -1) nextIndex = 0;

    used.add(nextIndex);
    await prefs.setString(_key, jsonEncode(used));

    return kLoveNotes[nextIndex];
  }

  static List<int> _getOrder(SharedPreferences prefs) {
    final raw = prefs.getString(_shuffleKey);
    if (raw == null) {
      final order = _newShuffledOrder();
      prefs.setString(_shuffleKey, jsonEncode(order));
      return order;
    }
    return List<int>.from(jsonDecode(raw) as List);
  }

  static List<int> _getUsed(SharedPreferences prefs) {
    final raw = prefs.getString(_key);
    if (raw == null) return <int>[];
    return List<int>.from(jsonDecode(raw) as List);
  }

  static List<int> _newShuffledOrder() {
    final list = List<int>.generate(kLoveNotes.length, (i) => i);
    list.shuffle();
    return list;
  }
}

/// The placeholder the name-bearing notes carry.
const String kLoveNoteNameToken = '{name}';

/// Fills the [kLoveNoteNameToken] placeholder carried by the notes that use
/// one. Notes without it come back unchanged.
String renderLoveNote(String template, String name) =>
    template.replaceAll(kLoveNoteNameToken, name.trim());

/// The name the notes address her by. Persisted so it is asked once, not on
/// every send. Required before any note is shown: 155 of the 250 paragraphs are
/// written around the name, and an empty value would ship `{name}` verbatim.
class LoveNoteRecipient {
  static const _key = 'love_note_recipient_name';

  /// Saved name, or null when nothing usable has been stored yet.
  static Future<String?> get() async {
    final name =
        (await SharedPreferences.getInstance()).getString(_key)?.trim();
    return (name == null || name.isEmpty) ? null : name;
  }

  static Future<void> set(String name) async =>
      (await SharedPreferences.getInstance()).setString(_key, name.trim());

  /// Sign-out calls this: the name is another couple's relationship PII, and
  /// device-scoped it survived into the next account — which then sent love
  /// notes auto-addressed to the previous partner's name.
  static Future<void> clear() async =>
      (await SharedPreferences.getInstance()).remove(_key);
}
