/// Lighter mini-game decks for the Games section, in Roman Urdu. These are
/// played locally (one phone, or read out on a call) — quick, sweet, flirty.

const wouldYouRatherDeck = <String>[
  'Ek hafta sirf meri baahon mein so sako ya ek mahina roz video call par baat — kya chuno ge?',
  'Mujhe roz subah uth kar kiss karo ya roz raat sone se pehle — ek choose karo.',
  'Saari zindagi sirf meri awaaz sun sako ya sirf meri tasveerein dekh sako?',
  'Hamari agli mulaqat lambi par door ho ya choti par abhi — kya behtar?',
  'Tum mujhe surprise visit karo ya main tumhe — behtar surprise kaun dega?',
  'Ek raat sirf baatein ya ek raat sirf cuddle bina kuch bole — kaunsi?',
  'Long drive haath mein haath ya barish mein bheegte hue saath — kaunsa?',
  'Meri awaaz mein recorded message rakho hamesha ya mera handwritten love letter?',
  'Saara din gale lage raho ya saara din ek dusre ko tease karte raho?',
  'Slow dance candle light mein ya midnight walk chand ke neeche?',
  'Ek dusre ki aankhon mein 5 minute bina hile dekho ya 5 minute non-stop baatein?',
  'Meri god mein sar rakh kar so jao ya main tumhari god mein — kaun?',
  'Mujhe apni har secret bata do ya meri har secret jaan lo?',
  'Honeymoon pahaadon par ya samandar kinare — abhi decide karo.',
  'Mujhe roz ek naya pyaar bhara naam do ya roz ek nayi tareef?',
  'Ek dusre ke liye gaana gao ya saath dance karo — kya choose?',
  'Mujhe har naraazgi par manao ya har khushi sabse pehle batao?',
  'Saari raat jaag kar baatein ya khamoshi mein ek dusre ko mehsoos karte raho?',
  'Mere shehar shift ho jao ya main tumhare — pehel kaun kare?',
  'Mujhe apni jacket pehna do thand mein ya apni baahon mein chhupa lo?',
];

const neverHaveIEverDeck = <String>[
  'Maine kabhi tumhari purani chat upar scroll karke dobara nahi padhi.',
  'Maine kabhi tumhari photo dekh kar muskuraate hue screenshot nahi liya.',
  'Maine kabhi kaam ke beech tumhari yaad mein kho kar waqt nahi guzaara.',
  'Maine kabhi tumse baat karte hue jaan-boojh kar so jaane ka natak nahi kiya.',
  'Maine kabhi tumhari kisi aur se hansi par halki si jealousy feel nahi ki.',
  'Maine kabhi "good night" ke baad bhi tumse ghanton baat nahi ki.',
  'Maine kabhi tumhe impress karne ke liye apni DP baar baar nahi badli.',
  'Maine kabhi tumhari awaaz sunne ke liye ek voice note replay nahi kiya.',
  'Maine kabhi tumhare saath future ke ghar ka sapna nahi dekha.',
  'Maine kabhi naraz hote hue bhi tumhare message ka intezaar nahi kiya.',
  'Maine kabhi tumhe dekh kar "kaash abhi paas hote" nahi socha.',
  'Maine kabhi tumhari koi cheez apne paas rakhne ka mann nahi kiya.',
  'Maine kabhi tumse jhoot bola ke "main theek hoon" jab main nahi tha/thi.',
  'Maine kabhi tumhari ek baat par poori raat soch kar nahi guzaari.',
  'Maine kabhi tumhe propose karne ka scene apne dimaag mein nahi banaya.',
  'Maine kabhi tumhari yaad mein koi gaana baar baar nahi sunaa.',
  'Maine kabhi tumhare saath ki koi baat kisi dost ko fakhr se nahi batayi.',
  'Maine kabhi tumhe miss karte hue tumhari purani photos nahi dekhi.',
  'Maine kabhi socha nahi ke tum meri zindagi ka sabse acha faisla ho.',
  'Maine kabhi tumhare naam ke aage chupke se dil wala emoji nahi lagaya.',
];
