-- ───────────────────────────────────────────────────────────────────────────
-- SUPERSEDED — 2026-08-17. This file is now a no-op, deliberately.
--
-- It was written to re-attach message_notify_on_insert to public.messages. It
-- was never applied to any database, and it could not have been, for two
-- independent reasons.
--
-- 1. ITS PRECONDITION CANNOT BE SATISFIED. The guard refused to run unless
--    public.notify_message() consulted push_muted(), and named 20260816120000
--    as the migration that would put it there. 20260816120000 does no such
--    thing — it says so in its own body ("notify_message and notify_call are
--    deliberately NOT touched here"), and its verify loop covers notify_reach
--    and notify_care only. Confirmed on production, where 20260816120000 IS
--    applied (ledger 20260815222837 ugc_terms_reports_and_contact_pause) and
--    pg_get_functiondef('notify_message') contains no mention of push_muted.
--
--    So the guard raised unconditionally: on production, and on a fresh
--    database replaying this directory in order. Left as it was, this file
--    ABORTS the bootstrap of every new environment — including staging.
--
-- 2. WHAT IT WOULD HAVE DONE IS NO LONGER WANTED. Re-attaching the original
--    trigger sends FCM kind 'message', and every handset already in the field
--    draws a visible banner for that kind (reach_notifications.dart:399 →
--    showMessageNotification). Those builds are sideloaded with no update
--    channel, so the branch is permanent. The owner does not want message
--    notifications; the requirement is a delivery TICK, not a banner.
--
-- The trigger is restored by 20260817110000_message_delivery_wake.sql, which
-- points notify_message() at kind 'msg_sync' — a kind no shipped client
-- recognises, so it draws nothing anywhere and wakes the app only long enough
-- to ack delivery. That file also explains why the push_muted gate this one
-- demanded is the wrong design for a receipt as opposed to a notification.
--
-- Emptied rather than deleted: the filename is the only breadcrumb from
-- BRAIN §38 and the 2026-08-15 production audit to the migration that actually
-- did the work, and a reader who greps for "restore_message_push_trigger"
-- should land on that pointer instead of on nothing.
--
-- Second run: no-op, as is the first.
-- ROLLBACK: none required — this file makes no change to roll back.
-- ───────────────────────────────────────────────────────────────────────────
