// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC93dDXEKQNImZF05YiLSZQE-2GhXQ8SDA',
    appId: '1:188998306037:web:5f394d3ffd0f97460dddbc',
    messagingSenderId: '188998306037',
    projectId: 'ldrc-120a2',
    authDomain: 'ldrc-120a2.firebaseapp.com',
    storageBucket: 'ldrc-120a2.firebasestorage.app',
    measurementId: 'G-0RZYMQL3Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHUOM-Hz1midmM-uAqfQrJw97i_8xHdPw',
    appId: '1:188998306037:android:32baecc398a397210dddbc',
    messagingSenderId: '188998306037',
    projectId: 'ldrc-120a2',
    storageBucket: 'ldrc-120a2.firebasestorage.app',
  );

  // Registered 2026-09-09 in the SAME Firebase project as Android (ldrc-120a2)
  // for bundle com.miles.miles, so the two platforms share one sender id and
  // one storage bucket. Values transcribed from ios/Runner/
  // GoogleService-Info.plist, which is the file the native SDK actually reads
  // at runtime; this class is what firebase_core uses from Dart. If they ever
  // disagree the plist wins on iOS, so regenerate BOTH from the console rather
  // than editing one.
  //
  // apiKey here is the iOS client key. Like the Android one it ships in the
  // build by design and is scoped by bundle id - it is an identifier, not a
  // credential. No Firestore, RTDB, Firebase Storage or Firebase Auth runs in
  // this app; only firebase_core and firebase_messaging.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUIfiCJU4GyCsCOPXPuu9YwJyG72QqOoU',
    appId: '1:188998306037:ios:99847ecfc0e9a2930dddbc',
    messagingSenderId: '188998306037',
    projectId: 'ldrc-120a2',
    storageBucket: 'ldrc-120a2.firebasestorage.app',
    iosBundleId: 'com.miles.miles',
  );
}
